### ISSUE TITLE
Will this ever be implemented for Oracle DB?

### ISSUE THREAD

**Issue by alexandis** [borisdj/EFCore.BulkExtensions#1025]
Since there is no way to ask a question - I have created the issue.

**Comment by borisdj** [comment]
No plan for it.

**Comment by alexandis** [comment]
OK, I see. Before I go forever :) - I'd like to ask one more question. I've tried to start implementing Oracle extension by myself - to figure out if it would be very complex. And now I'm stuck here. Could you please tell me if there's some trick adding a new DB? The project contains the reference to `EFCore.BulkExtensionsCore`, but I'm still getting the following exceptions for all extension methods trying to compile the project in VS:

![image](https://user-images.githubusercontent.com/6149843/207132842-4c657706-2569-4372-bfc2-9db7a7cd4a0c.png)

**Comment by borisdj** [comment]
I've restructured project.
There is no more Core project, instaed main project is with all providers, while per provider project are using **_Include_** to link source files, all expect other provider files, from the main.
So that the latest source version, add Oracle provider in the main project, and then write files per that provider like is done for others. The specialized project for separate Nugets can be created later if you manage to finish Bulk CRUD methods.

**Comment by borisdj** [comment]
New code update, source files and now copied with .bat script from main project when creating new version of per provider nuget

**Comment by borisdj** [comment]
@alexandis have you managed to make anything regarding Oracle support? to share the info

**Comment by alexandis** [comment]
Hi @borisdj - alas no: our project is in the tight timeframe, so I had to give up and start using solely EntityFramework, optimizing the code as much as possible (i.e. splitting into chunks, etc.)

**Comment by doanhieu9797** [comment]
@borisdj you have plan for Oracle?

**Comment by borisdj** [comment]
Dupe: https://github.com/borisdj/EFCore.BulkExtensions/issues/1113
