### ISSUE TITLE
Type Conversion failure in CheckHasIdentity()

### ISSUE THREAD

**Issue by gm112** [borisdj/EFCore.BulkExtensions#11]
It would seem the cast that's happening right in the while loop causes an exception in cases where there are no identities. I'm not entirely sure if this is something weird propagating in the environment I'm working with or if this is merely something else..

## Steps to Reproduce

1. Create a table that has a PK column which lacks any identity/auto-increment attributes so it sits as a normal column with the rest.
2. Set BulkConfig to SetOutputIdentity to true. (i.e. new BulkConfig { SetOutputIdentity = true })
3. Attempt a BulkInsert call. (haven't tested but this likely affects the other insertion methods as well)

## Solution / Notes

In any case, the offending line is occurring in TableInfo.cs right [here](https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/TableInfo.cs#L80).

For fixing the problem, I was able to simply alter the statement to the following:
`hasIdentity = reader[0] == DBNull.Value ? 0 : 1;`

Though I haven't exactly spent time investigating this issue further so if it ends up being some kind of weird false positive due to my environment then I do apologize in advance for occupying your time. Please let me know if there's any further information you would need.

Thanks!

**Comment by borisdj** [comment]
First I am not quite sure why are you doing it this way.
SetOutputIdentity is useful when Table HAVE Identity PK.
If it does not have Identity it means that you have to set PKs in memory in which case you already have them and there is no need for DB to return them back.

However I have tried even this unusual situation and it works, so can not reproduce your issue.
You can test this easily by adding Attribute to ItemId in class Item (TestContext.cs) :
````
public class Item
{
	[DatabaseGenerated(DatabaseGeneratedOption.None)]
	public int ItemId { get; set; }
````
This will create ItemId  as PK but without Identity.
IF you have already run Tests then first delete EFOperationsTest db from your local sql server, so that tables gets created again.
