### ISSUE TITLE
Custom default value for boolean fields are ignored

### ISSUE THREAD

**Issue by attmik** [borisdj/EFCore.BulkExtensions#1104]
I have a data model where a boolean field has its default value defined as "TRUE" in the EF model, and in the db schema as well. 

When using bulk inserts and passing a record set where ALL entities has this field set as "FALSE", those will be stored in the DB with "TRUE". If there is at least one entity that has a different value than "FALSE" the the records are created properly.

My assumption is that the bulk insert ignores those fields from the insert query that has their value set to default on all entities to leave it to the  SQL server to set the default instead. But this would only work if the engine would consider the actual default value of the field.

I have tried to use the PropertiesToInclude config option, but seemed to have no effect on this. Is there any way to overcome this situation?

**Comment by borisdj** [comment]
There a comment in the code about this
https://github.com/borisdj/EFCore.BulkExtensions/blob/4691ee632f4908b0f3a6c9840c2390c664ea86d0/EFCore.BulkExtensions/TableInfo.cs#L339-L344

So if all in list have default value (for bool it is 'FALSE') then they will be omitted from Insert and Database will set them, otherwise they are inserted explicitly with values from their property.

So if you need True just set them as True, or at least the first one to have desired behavior.
