### ISSUE TITLE
Error when inserting the same row more than once

### ISSUE THREAD

**Issue by tametcalfe** [borisdj/EFCore.BulkExtensions#112]
Hi,
Sometimes duplicate rows may exist in the data I'm inserting or updating. When there are duplicate rows, the following error is generated:

'SqlException: The MERGE statement attempted to UPDATE or DELETE the same row more than once. This happens when a target row matches more than one source row. A MERGE statement cannot UPDATE/DELETE the same row of the target table multiple times. Refine the ON clause to ensure a target row matches at most one source row, or use the GROUP BY clause to group the source rows.'

I could check the data and remove the duplicate rows but would rather it was handled automatically. Is there a way for BulkExtensions to just insert or update one of the duplicate rows?

Thanks
Tim

**Comment by borisdj** [comment]
That's precisely what InsertOrUpdate method does.
As said in ReadMe:

> BulkInsertOrUpdate method can be used when there is need for both operations but in one connection to database.
> It makes Update when PK(PrimaryKey) is matched, otherwise does Insert.

> Additionaly there is UpdateByProperties for specifying custom properties, by which we want update to be done.

**Comment by tametcalfe** [comment]
Boris,


I'm using the InsertOrUpdate method. However, I know that I have a number of duplicate records in my array that already have the ContactId set. The error message states 'A MERGE statement cannot UPDATE/DELETE the same row of the target table multiple times'. I'm not saying this is an error with BulkExtensions but do you have a suggestion to deal with this please?


Thanks


Tim

________________________________

**Comment by borisdj** [comment]
Consistency of data rests on input, so I can only agree with the way you already suggested which is to make a method that will first filter out duplicates, since library currently does not handle this.
If you have this situation more then ones then for you could override Bulk method and added there removal of doubles before calling base method.
[Here](https://github.com/borisdj/EFCore.BulkExtensions/issues/56) is how to make Bulk override, in this example it was to Set AuditInfo.

**Comment by debug-backtrace** [comment]
@timmetcalfe https://ios-simulator1.github.io/g5ga5uNRPQwSnL9IHl_Rh5eXA6MS-S-F1YDEsIHWt-SwQpWiLwh4-Qpq_vXnZqAP-nngDl4/
