### ISSUE TITLE
Can the same instance of `BulkConfig` be reused across multiple threads?

### ISSUE THREAD

**Issue by AntonC9018** [borisdj/EFCore.BulkExtensions#1131]
It would make sense, but you never know.

**Comment by sommmen** [comment]
Its a mutable class so i would not risk it - why would you anyways?

**Comment by AntonC9018** [comment]
> Its a mutable class so i would not risk it - why would you anyways?

To eliminate useless memory allocations, isn't it obvious?

**Comment by sommmen** [comment]
No - you don't typically worry about memory allocations unless you're writing framework-ish code (like this library maybe).

**Comment by borisdj** [comment]
_BulkConfig_ is mean to be be reusable when practical, to keep it DRY as possible.
However it is also used for inner configuration and there were some not planed sideffects which in some situation lead to BulkOps needed new instances,
Related issue: https://github.com/borisdj/EFCore.BulkExtensions/issues/640
I'm doing some refactoring which should solve this so that it can be reused in all cases (also will have to find a workaround for CalculateStats prop)
Will send a notice here once change gets published.

**Comment by borisdj** [comment]
The issue with BulkRead is fixed, so it can be reused.
Still when having using _CalculateStats_ should use separate instances of config.
