### ISSUE TITLE
ChangeTracker and BulkInsertOrUpdate

### ISSUE THREAD

**Issue by Billy-J-Joseph** [borisdj/EFCore.BulkExtensions#1143]
When I used BulkInsertOrUpdate and BulkDelete on the child of an aggregate root in DDD, the ChangeTracker detected changes on all properties, not only the ones that have been modified. 

I couldn't find clear documentation about how BulkExtensions affect the EF Core change tracking, so I need confirmation if that's not the case.

**Comment by borisdj** [comment]
Main usage of Bulk CRUD Ops are without tracking since tracking makes it slower.
Still it can be used in some cases.
For example BulkConfig has TrackingEntities which can be set to True if we want to have tracking of entities from BulkRead or if SetOutputIdentity is set.
Also When using BulkSaveChanges it uses Change Tracker to find all modified(CUD) entities and call proper BulkOperations for each table.
But I am not sure there is differentiation on same vs modified columns.
You culd first BulkRead data and make diff in memory if you need it.

**Comment by borisdj** [comment]
Glad its useful.
