### ISSUE TITLE
BulkInsert in a 1:1 relationship without Identity on PK column

### ISSUE THREAD

**Issue by NorbertKessler** [borisdj/EFCore.BulkExtensions#1163]
Hello, 
I'm struggling using the component in a scenario where I have to Insert (or Update) a table using the Primary Key column (int) as key but not having an identity definition on it. 
Just using the component tells me I send NULL in the Id column which of course cannot be NULL. Using Options like KeepIdentity results in an error saying I don't have an identity definition on that column. So is there a way using the component in this scenario ?

**Comment by borisdj** [comment]
Assuming you have list in which some are to be update and have ID value, while others are to ne inserted.
In regular situation you could leave IDs to be zero '0' for those should be inserted, and Identity constrain would give them values in DB.
So if you do even without Identity do have this table in DB configured with DbGenerated that it should work the same, otherwise you need to set those IDs before insert (first read the latest and then increment from there)
