### ISSUE TITLE
Change of version from 6.7.12 to 6.7.15 highly impacts on performance

### ISSUE THREAD

**Issue by NachoGrost** [borisdj/EFCore.BulkExtensions#1212]
For some reason, I have an application in .Net Core 6.0 that used the 6.7.12 version, and that worked just fine. When I update it to 6.7.15 the performance highly decreased.
In 6.7.12 a BulkRead + BulkInsertOrUpdate took about 3-5 sec.
In 6.7.15 a BulkRead + BulkInsertOrUpdate took about 4-5 min.
I didn't verify internally what was triggering this, I need to continue so I will just use the 6.7.12 version, but I wanted to post this issue I encountered for future updates.

**Comment by axelgenus** [comment]
We also noticed this issue and I am currently investigating the root cause. A workflow of ~20 merge operations took about 3 minutes and now takes +1 hour to complete (and sometimes EFCore just times out).

I did not compare the generated merge statements yet, but I noticed that the current version hints at using LOOP JOINS and that could be an issue with very big tables (of similar size).

**Comment by axelgenus** [comment]
I guess there is an issue here:

![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/4807085/76209273-d411-4e4c-91e7-bd76c1221c33)

**Comment by borisdj** [comment]
The issue is now obvious.
@axelgenus great debugging.
For now fix is to set it explicitly to False, as you already mentioned, and I'll correct it to True with next version.
