### ISSUE TITLE
BulkInsert with IncludeGraph = true  not working as expected

### ISSUE THREAD

**Issue by mr-xrow** [borisdj/EFCore.BulkExtensions#1314]
Hi @borisdj,
```
 public class A
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public List<B> Children {get;set;}
}

public class B
{
    public Guid Id { get; set; }
    public Guid IdOfA { get; set; }
    public string NameOfA {get;set;}
}

    var lstA = new List<A>();
    for (var i = 0; i < 3; i++)
    {
          var a = new A {Id=Guid.NewGuid(),  Name = $"A {i + 1}", Children = new List<B>() };
          for (var j = 0; j < 3; j++)
          {
               var b = new B { Id=Guid.NewGuid(), IdOfA = a.Id, NameOfA = $"{a.Name}" };
               a.Children.Add(b);
           }
           lstA.Add(a);
     }

   context.BulkInsert(entities, new BulkConfig {IncludeGraph = true});
```
Result from SQL Server:

```
A1: {Id:'guidA1', Name:'A 1'}
A2: {Id:'guidA2', Name:'A 2'}
A3: {Id:'guidA3', Name:'A 3'}

B1: {Id:'guidB1', IdOfA:'guidA1', NameOfA: 'A 2'}
B2: {Id:'guidB2', IdOfA:'guidA2', NameOfA: 'A 3'}
B3: {Id:'guidB3', IdOfA:'guidA3', NameOfA: 'A 1'}
...
```
I think that during the insert process into sql, the Id value of table A was messed up.

**_EFCore.BulkExtensions: 6.7.16
NET: 6
Microsoft.EntityFrameworkCore:6.0.21_**

**Comment by RobinGitHub** [comment]
Me too

**Comment by tiggris** [comment]
Hi! 

Recently we've experienced the same issue. After vast investigation with library debugging it seems that issue is related to updating entities identity - in our case we use GUIDs and such an update is unnecessary. I've tried to use different configurations to overcome that issue like setting BulkConfig.SetOutputIdentity = false, but unfortunately it didn't work as some configuration values are overridden when IncludeGraph = true. The workaround that seems to work is to give up on graph and bulk insert all dependent collections separately:

```
var config = new BulkConfig { IncludeGraph = false };
context.BulkInsert(entities, config);
context.BulkInsert(entities.SelectMany(entity => entity.DependentCollection1).ToList(), config);
context.BulkInsert(entities.SelectMany(entity => entity.DependentCollection2).ToList(), config);
```

I was trying to find a fix for that issue, but the complexity of the solution is too high to do it without deep understanding of the library mechanics. I can only point out where the issue occurs and why.

[`TableInfo.LoadOutputDataAsync()`](https://github.com/borisdj/EFCore.BulkExtensions/blob/73598a972d77b8f60f8be98c22fa977cf19fdd5f/EFCore.BulkExtensions/TableInfo.cs#L1200):
```
var entitiesWithOutputIdentity = QueryOutputTable(context, type, sqlQuery).Cast<object>().ToList();
UpdateEntitiesIdentity(tableInfo, entities, entitiesWithOutputIdentity); // here entitiesWithOutputIdentity contains elements in different order than entities collection
```

[`TableInfo.UpdateEntitiesIdentity()`](https://github.com/borisdj/EFCore.BulkExtensions/blob/73598a972d77b8f60f8be98c22fa977cf19fdd5f/EFCore.BulkExtensions/TableInfo.cs#L1131):
```
var element = entitiesWithOutputIdentity.ElementAt(i); // here ElementAt(i)
var identityPropertyValue = outputIdentityOnly ? element : FastPropertyDict[identifierPropertyName].Get(element);
FastPropertyDict[identifierPropertyName].Set(entities.ElementAt(i)!, identityPropertyValue); // would be different than ElementAt(i) here as the order of elements in both collections is different
```
----------------------------------------------------------------
_**EFCore.BulkExtensions: 8.0.2
NET: 8
Microsoft.EntityFrameworkCore: 8.0.4**_

**Comment by akordowski** [comment]
I discovered the same issue today and it took me hours to find the cause.

Here my scenario: I have a list with parent objects which contain a list of child objects. The `ResourceId` and the `ParentId` of the child object are the same. All objects have string IDs and the order can be random. The items are imported in the DB and the IDs are already set in the objects.

```
var list = new List<Parent>
{
    new()
    {
        ParentId = "def",
        Children = new List<Child>
        {
            new() { ResourceId = "def", ParentId = "def", Type = ChildType.Small },
            ...
        }
    },
    new()
    {
        ParentId = "abc",
        Children = new List<Child>
        {
            new() { ResourceId = "abc", ParentId = "abc", Type = ChildType.Small },
            ...
        }
    },
    new()
    {
        ParentId = "jkl",
        Children = new List<Child>
        {
            new() { ResourceId = "jkl", ParentId = "jkl", Type = ChildType.Small },
            ...
        }
    },
    new()
    {
        ParentId = "ghi",
        Children = new List<Child>
        {
            new() { ResourceId = "ghi", ParentId = "ghi", Type = ChildType.Small },
            ...
        }
    },
};
```

After the insert with `IncludeGraph = true` all records in the `Parent` and `Child` table are in ascending order by the ID, but the childs `ParentId` is in the same order as the collections order and don't match with the `ResourceId`.

![grafik](https://github.com/borisdj/EFCore.BulkExtensions/assets/9746197/28fbe995-5661-4dd9-aee4-3faad663469a)

 The only solution was to sort the original list by the `ParentId` in ascending order. In that case the childs `ParentId` matched with the `ResourceId`.

This behavior is the same with all this methods:

```
BulkInsert()
BulkInsertOrUpdate()
BulkInsertOrUpdateOrDelete()
```

I appended a test project with which the behavior can be reproduced.
[EFCoreBulkExtensionsTest.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/15049069/EFCoreBulkExtensionsTest.zip)

**Comment by akordowski** [comment]
@borisdj I encountered this issue today again. The objects values were different as in the example above, but now even the sorting didn't helped. This is imo a critical issue when the data consistency cannot be trusted. Could you please take a look? Thank you for your effort!

**Comment by akordowski** [comment]
@borisdj I could track down the issue to the `TableInfo.cs` class. As you can see in the screenshot below the `entitiesWithOutputIdentity` (loaded from the database) are sorted by the `PK` and the `entities` are as the were passed to the method.

![screenshot_1](https://github.com/borisdj/EFCore.BulkExtensions/assets/9746197/67656398-214d-4879-a907-3bd6f08c627f)

In the line `1134` the identity of the children is set and as you can see after that the ID value changes.

![screenshot_2](https://github.com/borisdj/EFCore.BulkExtensions/assets/9746197/1854e80e-d8a1-4627-9a68-beb0296bb85f)

![screenshot_3](https://github.com/borisdj/EFCore.BulkExtensions/assets/9746197/b7fb49be-8695-4e71-9ba4-b040937b046c)

I assume this results from the nature of `string` keys. Or the problem is that the PK are already set, no matter if `string` or `int`. I haven't tested it yet with numeric `PKs` and with entities where the `PK` is not set.

I think when the `entities` were sorted as the `entitiesWithOutputIdentity`  are I could solve the problem. What do you think?

**Comment by akordowski** [comment]
A test with `numeric PKs` only looks good. It seams only to affect records with `string PKs`.

**Comment by akordowski** [comment]
@borisdj I created a PR #1475 which in my tests fixed the issue. Please take a look. Thank you!

**Comment by borisdj** [comment]
Hi all, @akordowski will take a look, thx for contrib.
