### ISSUE TITLE
System.ArgumentOutOfRangeException when BatchDelete using Npgsql for PostgreSQL

### ISSUE THREAD

**Issue by amazedevil** [borisdj/EFCore.BulkExtensions#132]
Making simple query:

```
DB.Item
    .Where(x => x.OtherItemId == itemId)
    .BatchDelete()
```

and getting exception

```
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql[T](IQueryable`1 query)
   at EFCore.BulkExtensions.BatchUtil.GetSqlDelete[T](IQueryable`1 query)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDelete[T](IQueryable`1 query)
```

**Comment by borisdj** [comment]
Write more info on how to reproduce the issue or simulate it in BatchTest with RunBatchDelete.

**Comment by aviezzi** [comment]
Same issue for me with Npgsql.EntityFrameworkCore.PostgreSQL 2.1.1.1

await Context.Set<UserEvent>().Where(ue => ue.EventId == entity.Id).BatchDeleteAsync();

**Comment by borisdj** [comment]
Library does not support **PostgreSQL** currently.
However since Batch is not using _SqlBulkCopy_(SQL Server specific) but only pure sql commands it could easily be adapted.
So according to the `sqlQuery` you posted difference with _Npgsql_ provider seems to be that `tableAlias` does not contains brackets `[ ]`:
`SELECT ue."Id", ue."EventId", ue."UserId"`
vs
`SELECT [a].[Column1], [a].[Column2]`
So try changing that line of code with:
```C#
string escapeSymbol= sqlQuery.Contains("]") ? "]" : "."; // or make this IF depending on provider used
string tableAlias = sqlQuery.Substring(8, sqlQuery.IndexOf(escapeSymbol) - 8);
```
I don't have PostgreSQL installed at the moment so can't test this.
But you are free to try make it work and if it's successful make a Pull request.
It's probably the case that variable `escapeSymbol` would have be used wherever brackets are currently hardcoded.

**Comment by alexb5dh** [comment]
As as note, this also affects SQLite.

**Comment by ZeekoZhu** [comment]
SQLite use double quotes as `escapeSymbol`:

```sql
SELECT "x"."EntryID", "x"."BlogId", "x"."IsActive", "x"."EntryID", "x"."TagID"
FROM "blog_Entry" AS "x"
WHERE ("x"."IsActive" = 0)
```

**Comment by borisdj** [comment]
SQLite is now supported from version 2.6.0

**Comment by ThomasBergholdWieser** [comment]
Same happens when using MySQL

**Comment by borisdj** [comment]
https://github.com/borisdj/EFCore.BulkExtensions/issues/67
