### ISSUE TITLE
Is it possible to insert master-detail info in one shot

### ISSUE THREAD

**Issue by nafberger** [borisdj/EFCore.BulkExtensions#18]
I would like to know if you can use BulkInsert to insert a master-detail record in one shot.
see scrennshot
![screenshot_3](https://user-images.githubusercontent.com/26122027/29389323-5e7d303a-82b7-11e7-963b-5c53c321b124.png)

**Comment by borisdj** [comment]
It is not.
This would be quite complex to implement since you could have tree of nested elements and would have go through entire depth of that structure, analysing each table and what to insert first.
The way you do it with bulk operations is that you first add the parent, via regular Add or using BulkInsert if there are a lot of them as well.
And then you add Child element by sending list<Child> in Bulk Insert.
Here usually is where SetOutputIdentity is used because if Id is generated in Db you need it back so you can set their FK in Child objects.

**Comment by nafberger** [comment]
So how do you use SetOutputIdentity, what does return, a list of the newly inserted id's. ?

**Comment by borisdj** [comment]
Not list of Id-s, but list of entities themselves, the list that you have send, it just updates Id Property.
It is explained in README, Paragraph **SetOutputIdentity**.

**Comment by nafberger** [comment]
Can you please explain how It works, i am passing in a list of entities for inserting, but even after using BulkInsert and set output identity as true, noting is updated in the entities list, the id remains 0 as before inserting, please explain. thank you. can you show me a code snippet

this is my code: I expect list to have the changes

 public void InsertBulk(List<PurchaseItem> list)
        {
           _context.BulkInsert(list, new BulkConfig { SetOutputIdentity = true});
        }

**Comment by nafberger** [comment]
Also Borris, I am running into timeout problems when inserting thousands of records, how do I increase timeout, will that help?

**Comment by borisdj** [comment]
There was a small bug with SetOutputIdentity which is now fixed in 2.0.1 version.

**Comment by nafberger** [comment]
Big thanks for your help, just asking do you always see comments even on closed issues?, what is the proper way to ask something, open a new issue? is opening new issues a problem? sorry for asking, I am fairly new to the github world

**Comment by borisdj** [comment]
Yes, I get the notification about comments even on closed issues.
I guess the good rule would be to ask questions even on closed issues if they are about the issue itself, and if it is unrelated question about another thing then to open a new issue, regardless whether others issue are opened or closed.
