### ISSUE TITLE
Bulk Insert Should Update ID's

### ISSUE THREAD

**Issue by RehanSaeed** [borisdj/EFCore.BulkExtensions#2]
I am doing a bulk insert but would then like to get the entities I am inserting to have their primary keys updated. Right now, they stay as zero. I would like to do this so I can bulk insert related entities but I need to set the foreign key.

How can I achieve this?

**Comment by borisdj** [comment]
I assume your table have Db Identity, meaning PK is created in Database.
In that case you should just load inserted entites with standard EF select from DbSet.
If your table was empty you can select entire table:
`var query = context.Set<SomeEntity>();`
Otherwise you have to add filter, for example by TimeCreated or some other property by which you can identify inserted entities:
`var query = context.Set<SomeEntity>().Where(a => a.TimeCreated = timeCreated );`

And if your Id is int-autoincrement, you could select last Id before insert and then after set Id-s of inserted entites in memory.
So for example if last id was 112, and you add 15 entities you would set it's Id-s to 113, 114, ..., 127.
This way you don't need additional Select of all entities.

**Comment by RehanSaeed** [comment]
I have multiple inserts happening at the same time, so I need a reliable way to get back the primary key ID's for the inserted entities. I could add a GUID column to my table for this purpose but that's a lot of extra work. Is there no alternative?

**Comment by RehanSaeed** [comment]
I should also mention I have a three level hierarchy of related tables I need to bulk insert. There doesn't seem to be a good way of doing this.

**Comment by borisdj** [comment]
I understand your problem.
I didn't have this situation so far because we use Guid for Id that are created in memory, not in DB, SequentuialGuids to be precise because of clustered index efficiency.
Currently I don't see other options then the ones I've already mentioned.

However after giving some thoughts to it and a little research I figured it could be implemented using [Output](https://stackoverflow.com/questions/7917695/sql-server-return-value-after-insert) command.
I will try to implement it as additional feature directly in BulkExtension library.

**Comment by borisdj** [comment]
I have updated the library with these features.
You can try it and see if it fits your needs.
More info is in README and there is also nuget update 1.0.3

**Comment by RehanSaeed** [comment]
I've switched to Dapper for now which has solved my high memory issues, so this has come a little late for me but I fully appreciate your efforts. I'll take another look at this if I get a chance.

**Comment by borisdj** [comment]
No problem, it's good to have multiple options.
And more features is always better, someone will find it useful.
