### ISSUE TITLE
Does It Work With Core 2.0?

### ISSUE THREAD

**Issue by nafberger** [borisdj/EFCore.BulkExtensions#20]
I got this error today after upgrading to core 2.0
![screenshot_4](https://user-images.githubusercontent.com/26122027/29900263-b3288668-8dbe-11e7-9cd0-00ed4777a991.png)

**Comment by borisdj** [comment]
I have just looked into this.
These seems to be problem with packages versions.
Cause of the problem is method `context.Database.ExecuteSqlCommand(...` (from _Relational_ package).
What is even more strange is that the exception is thrown form a line where another method is being called just because that method contains call to this `ExecuteSqlCommand_`.
So it was quite hard to find the bug.
Now this library uses _Microsoft.EntityFrameworkCore.Relational 1.1.2_ and it seems that is not compatible with 2.0
But if I switch 2.0 then older versions will not work.
One solution would be to have 2 nuggets but I would first like to check is both could be supported from single library.

**Comment by borisdj** [comment]
Single library can Not support both versions.
[https://github.com/aspnet/EntityFrameworkCore/issues/9653(https://github.com/aspnet/EntityFrameworkCore/issues/9653)

But I don't want to have 2 repos and 2 nugget either.
So I plan to make a switch to 2.0 soon and publish it as pre-release for some period so it can be used with 2.0 version.
And once I make a release anyone needing older versions will be able to install older nugget versions before this switch was made, but in the long run everybody should switch their projects to 2.0+

**Comment by nafberger** [comment]
Any Time Frame for the change?

**Comment by borisdj** [comment]
Next week.

**Comment by nafberger** [comment]
Oh good good, wish we can take you on our development team. our developer rushes always to the newest technology and it creates headaches, what is the benefit of jumping on the wagon at the earliest time

**Comment by borisdj** [comment]
:)
I have just released v1.0.8 where support for explicit transaction is added, which enables multiple bulk operations in single transaction.
README is updated with example of it.

**Comment by borisdj** [comment]
Prerelease 2.0.0-rc published.

**Comment by nafberger** [comment]
Good, Big Thanks
  ----- Original Message -----
