### ISSUE TITLE
BulkInsertOrUpdateAsync, Ids not setting correctly

### ISSUE THREAD

**Issue by joharzmn** [borisdj/EFCore.BulkExtensions#204]
I am using BulkInsertOrUpdateAsync function to addOrUpdate the entities into the database and i want to use the ids getting after function to use in the related entities. 
Here is my code: 
```csharp
await context.BulkInsertAsync(allHubTables, new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true });
                    foreach (var hubTable in allHubTables) {
                        foreach (var field in hubTable.HubFields) {
                            field.HubTableId = hubTable.Id;                           
                            allHubFields.Add(field);
                        }
                    }
```

**Problem**
After execution of this line:
```csharp
await context.BulkInsertAsync(allHubTables, new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true });
```
I have `ids` in `allHubTables`, but when i check the ids in the database after commit the transaction. They are different than the ids in `allHubTables` array.

**Note:** above code is inside the transaction

**Comment by borisdj** [comment]
Since you are using PreserveInsertOrder make sure to set Id as explain in the ReadMe:

>PreserveInsertOrder makes sure that entites are inserted to Db as they are ordered in entitiesList.
However for this to work Id column needs to be set for the proper order.
For example if table already has rows, let's say it has 1000 rows with Id-s (1:1000), and we now want to add 300 more.
Since Id-s are generated in Db we could not set them, they would all be 0 (int default) in list.
But if we want to keep the order as they are ordered in list then those Id-s should be set say 1 to 300.
Here single Id value itself doesn't matter, db will change it to (1001:1300), what matters is their mutual relationship for sorting.
 
>When using PreserveInsertOrder with SetOutputIdentity Id value does matter.
If it's BulkInsertOrUpdate method for those that will be updated it has to match Id.
And if we need to sort those for insert(BulkInsert/OrUpdate) and not have conflict with existing Id-s, there are 2 ways:
One is set Id to really high values, order of magnitude 10^10, and another even better setting them to negative values.
So if we have list of 8000, say 3000 for update (they keep the real Id) and 5000 for insert then Id-s could be (-5000:-1).

**Comment by joharzmn** [comment]
Okay Thanks @borisdj

**Comment by bunty996** [comment]
@borisdj I am facing same kind of issue I am pasting my code here with bit modification as per code privacy :-
```
var bulkConfig = new BulkConfig()
            {
                SetOutputIdentity = true,
                PreserveInsertOrder = true
            };   
var subEntities = new List<ItemHistory>(); 
await _dbContext.BulkInsertOrUpdateAsync(entities, bulkConfig);
    
foreach (var entity in entities)
{
   foreach (var subEntity in entity.ItemHistories)
    {
     subEntity.ItemId = entity.ID; // setting FK to match its linked PK that was generated in DB
    }
    subEntities.AddRange(entity.ItemHistories);
}
await _airportDBContext.BulkInsertOrUpdateAsync(subEntities})
```

Both Entity and subentity are upsert fine into db, but while I am checking into db for table itemHistory in which "ItemId" is referencing wrong entity. Could you please help me to out this.
