### ISSUE TITLE
Not able to add entities with 1 to one relationship

### ISSUE THREAD

**Issue by sergiosaint** [borisdj/EFCore.BulkExtensions#217]
Not sure if this is a bug, or poor usage by me...

If I have something like this a "SuperParent" that contains a dependent entity "SuperParentCape"
Doing something like this throws an exception:
```
using (var transaction = context.Database.BeginTransaction()) {
    context.BulkInsert(parents, new BulkConfig { SetOutputIdentity = true });
    transaction.Commit();
 }
```

`System.Data.SqlClient.SqlException: 'The MERGE statement conflicted with the FOREIGN KEY constraint "FK_SuperParents_SuperParentCapes_SuperParentCapeId". The conflict occurred in database "TestApp", table "dbo.SuperParentCapes", column 'SuperParentCapeId'.`

My assumption is that it is trying to add the Parent without having the id of the Cape

```
public class SuperParent {
    public int SuperParentId { get; set; }
    public string Name { get; set; }
    public int SuperParentCapeId { get; set; }
    public SuperParentCape SuperParentCape { get; set; }
 }

public class SuperParentCape {
    public int SuperParentCapeId { get; set; }
    public string Name { get; set; }
}
```

Is this possible to overcome?

**Comment by borisdj** [comment]
Just set the **SuperParentCapeId** propery of parents entities, if _SuperParentCape_ is already in Db.
Otherwise if you are adding them both at once, then you need to call BulkInsert 2 times, first for _SuperParentCapeList_ with **SetOutputIdentity**, after which set _SuperParentCapeId_, and then call BulkInsert for _SuperParentList_. More info is in the ReadMe under [BulkConfig](https://github.com/borisdj/EFCore.BulkExtensions#bulkconfig-arguments), segment:

> Example of SetOutputIdentity with parent-child FK related tables

**Comment by sergiosaint** [comment]
I think this is a feature request then, because in this scenario I cant use BulkInsert then, I will need to add the Capes one by one to update the Parents and then insert the parents.

A new bolean parameter to insert dependent entities would be nice
