### ISSUE TITLE
BulkUpdate - too many server round trips

### ISSUE THREAD

**Issue by CSharpBender** [borisdj/EFCore.BulkExtensions#229]
Using Sql Profiler I noticed that for a BulkUpdate, 6 server trips are done:
1. Identify PK - this can be extracted from EF meta information
2. The Temp table is created - the query is strange: from MyTable t left join MyTable source on 1=0
3. Returns table collation - ??
4. Bulk insert - The creation of the temp table and the insertion could be done at the same time
5.  6..  Merge, Drop table - these could be done in one server trip

**Comment by borisdj** [comment]
1. Can you write an example of reading IdentifyInfo from EF.
2. It does look unusual but creates what is required:
https://dba.stackexchange.com/questions/916/how-do-i-copy-a-table-with-select-into-but-ignore-the-identity-property
3. Can't find where that is called from?
4. Not sure about this since Creating is using pure SQL and Inserting is done using SqlBulkCopy that requires destination table already to exist.
5. This could be put in single query but I don't think gain would be significant since in Bulk Ops it's not the call to Sql but the amount of Data that was the bottleneck. Also for Readability, and Testing purposes keeping it separate is beneficial.

**Comment by CSharpBender** [comment]
I haven't tried this on EF, just on NHibernate and MongoDb.
The guys from zzzprojects are compiling the expression to extract the Id but it must be a better way.

After a quick search:
https://stackoverflow.com/questions/15718301/how-i-can-read-ef-dbcontext-metadata-programmatically
