### ISSUE TITLE
EnumToStringConverter value converter not being applied for BatchUpdate

### ISSUE THREAD

**Issue by alexb5dh** [borisdj/EFCore.BulkExtensions#241]
`Where` filter is not converting enum properties marked as `string` in EF configuration. Instead, it always serializes them as numbers.

Similar issue was fixed for `BulkInsert`: #140. But it still affects `BatchUpdate` and probably `BatchDelete`.

Can provide code to reproduce if needed.

**Comment by borisdj** [comment]
Please add code or test for reproducing the issue.

**Comment by alexb5dh** [comment]
I created a pair of tests but they seems to pass so it was either fixed in between or was related to some other issue. I changed original code some time ago so can't answer for sure.

Anyway here are is the test class I created. Feel free to adapt it as you like and add to your tests:
```csharp
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace EFCore.BulkExtensions.Tests
{
    public class StringEnumTest
    {
        [Fact]
        public async Task UpdateTest()
        {
            await ArrangeAsync();

            using (var context = new TestContext(ContextUtil.GetOptions()))
            {
                var query = context.Infos.Where(i => i.InfoType == InfoType.InfoTypeA);

                const string updateMessage = "29095a36-2705-4bac-ae86-f62322fba553";
                await query.BatchUpdateAsync(i => new Info { Message = updateMessage });

                var infos = await query.ToListAsync();

                Assert.NotEmpty(infos);
                Assert.All(infos, i => Assert.Equal(updateMessage, i.Message));
            }
        }

        [Fact]
        public async Task DeleteTest()
        {
            await ArrangeAsync();

            using (var context = new TestContext(ContextUtil.GetOptions()))
            {
                var query = context.Infos.Where(i => i.InfoType == InfoType.InfoTypeA);

                await query.BatchDeleteAsync();

                var infos = await query.ToListAsync();

                Assert.Empty(infos);
            }
        }

        private async Task ArrangeAsync()
        {
            using (var context = new TestContext(ContextUtil.GetOptions()))
            {
                context.Infos.AddRange(
                    new Info { InfoType = InfoType.InfoTypeA },
                    new Info { InfoType = InfoType.InfoTypeA },
                    new Info { InfoType = InfoType.InfoTypeB },
                    new Info { InfoType = InfoType.InfoTypeB }
                );
                await context.SaveChangesAsync();
            }
        }
    }
}
```

**Comment by marcin2x** [comment]
Issue seems to be back again.
BatchUpdate sets properties with EnumToStringConverter without converting them.
In DB we see "1" instead of converted value.
When reading, it's converted to value proper enum value, but when using Where statement, it doesn't work as db holds "1" instead of "Processing" which is expected enum value.

**Comment by brandonsmith86** [comment]
> Issue seems to be back again.
> BatchUpdate sets properties with EnumToStringConverter without converting them.
> In DB we see "1" instead of converted value.
> When reading, it's converted to value proper enum value, but when using Where statement, it doesn't work as db holds "1" instead of "Processing" which is expected enum value.

I am seeing the same thing with BulkInsertAsync and version 3.2.5.   I specify the converter using the pre-defined conversion method documented [here](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#pre-defined-conversions).  Records are inserted with integer representation of enum; took quite a few hours of troubleshoting to figure out why my foreign key constraints were failing.  Turned out to be caused by this issue.  I will put this same comment in the thread for BuilkInsert as well.
