### ISSUE TITLE
BulkInsertOrUpdateAsync with PreserveInsertOrder = true and SetOutputIdentity = true not working

### ISSUE THREAD

**Issue by martosource** [borisdj/EFCore.BulkExtensions#299]
I am having some issues with  BulkInsertOrUpdateAsync with PreserveInsertOrder = true and SetOutputIdentity = true not working.

The order of the List is not being kept.

Example with Updates only:
List Before BulkInsertOrUpdateAsync (Id, Name)
1 - Domestic
25 - United Kingdom
45 - Japan
36 - Singapore
37 - New Zealand
39 - Hong Kong
41 - Malaysia
42 - Taiwan
43 - Thailand
44 - United Arab Emirates
24 - Germany
23 - United States
22 - Sweden
21 - Finland
2 - Norway
3 - China
5 - Korea
7 - Denmark
8 - The Netherlands
9 - Canada
16 - Belgium
17 - Austria
18 - Malta
19 - Switzerland
20 - Nordics
46 - Indonesia

List After BulkInsertOrUpdateAsync (Id, Name)
1 - Domestic
2 - United Kingdom
3 - Japan
5 - Singapore
7 - New Zealand
8 - Hong Kong
9 - Malaysia
16 - Taiwan
17 - Thailand
18 - United Arab Emirates
19 - Germany
20 - United States
21 - Sweden
22 - Finland
23 - Norway
24 - China
25 - Korea
36 - Denmark
37 - The Netherlands
39 - Canada
41 - Belgium
42 - Austria
43 - Malta
44 - Switzerland
45 - Nordics
46 - Indonesia

The order of the input list is ignored and the output table is being sorted by primary key, so the list will never line up.

Why are updated records getting the PK set in TableInfo UpdateEntitiesIdentity?  Should this be only called for new records?

This is also an issue when there are new recording in the list as they are inserted first in the temp table the fake id but the are sorted in the output table.

I am running the latest EFCore (3.1.2) and EFCore.Bulk

**Comment by sergioprates** [comment]
Same problem here

**Comment by sergkr** [comment]
I'm not the library author, but since we ran into the same issue and spent a considerable amount of time investigating why it was occurring and how to work around it, I can shed some light on this.

When doing a bulk insert/update with `PreserveInsertOrder` and `SetOutputIdentity` both set to true, you actually have to set the IDs yourself prior to insert. These IDs are not the actual IDs that will be generated (since you can't know those before hand, and that defeats the point of `SetOutputIdentity`). However, the library uses these IDs to determine the insert order (apparently rather than just going off the order of the items in the list). After the bulk insert is performed, the IDs on the entities will be updated with the actual database-generated IDs.

**In addition**, these fake IDs that you set yourself must not conflict with any existing entries in the database. Any entries that have conflicting ID will not get inserted. For the most typical scenario with an `int ID` column that starts at 1, that rules out using the most obvious approach of setting the IDs to `0` through `N-1`.

This is all in the README, it's just not very well explained, in my opinion. It also seems the whole scheme is unnecessarily convoluted. I'm not sure why the library can't just preserve order based on the order of the items in the list.

So the way we've been doing it, and in case it helps anyone, we wrote a little facade helper method to do a bulk insert using this library without having to worry about the above details. It requires an expression that returns the ID column, and uses the order of the items in the list as the basis for preserving the insert order (by setting the ID column from -N to -1, which assumes that all existing entries have positive IDs):

```
public void InsertOrdered<T>(
    IList<T> entities,
    Expression<Func<T, int>> idProperty,
    BulkConfig bulkConfig = null,
    Action<decimal> progress = null)
    where T : class
{
    bulkConfig = bulkConfig ?? new BulkConfig();
    bulkConfig.PreserveInsertOrder = true;
    bulkConfig.SetOutputIdentity = true;

    var memberExpression = (MemberExpression) idProperty.Body;
    var idPropertyInfo = (PropertyInfo) memberExpression.Member;

    var n = entities.Count;
    for (var i = 0; i < n; i++)
    {
        var entity = entities[i];
        idPropertyInfo.SetValue(entity, i - n);
    }

    _context.BulkInsert(entities, bulkConfig, progress);
}
```

Example usage:

```
InsertOrdered(entities, e => e.Id);
```

**Comment by borisdj** [comment]
@sergkr you've explained it well.
The issue is that Insertion order is implemented with TOP in conjuction with ORDER BY, so the IDs need to be set with proper order.
But it could be done in the library itself, one approach being what you have used.
Although others scenarios should be consider, when PK is not int, like Guid etc.
However for the simple case the logic to convert zero '0' to order with negative numbers (as explaind in the ReadMe) is quite fine.
I will see to implement it in one of next version.

**Comment by DiegoStefanon** [comment]
to me is inserting wrong data ....
 very fast but wrong data insertion

**Comment by jamesrwaugh** [comment]
@DiegoStefanon I'm not sure if this is the same issue, but for me, when I insert `float` or `decimal` values they are always 0 in the DB regardless of the value in the code. I checked that right before insertion they have a value, but in the DB they are zero. @borisdj Do you have any ideas?

**Comment by borisdj** [comment]
As of now version 3.2.7+ when configured 'PreserveInsertOrder = true' Identity property (int autoincrement) has automatic Set from -N to -1, so no more need to set those values manually.
