### ISSUE TITLE
Could BulkUpdate specified conditions?

### ISSUE THREAD

**Issue by kexxxfeng** [borisdj/EFCore.BulkExtensions#3]
Hey:)
Thx for your EFCore.BulkExtensions very much. However, could BulkUpdate specify conditions? 
I want sql like this:
```sql
update [dbo].[table1] 
set [IsActive] = arg1
where [Id] = arg2 and [OrderId] = arg3
```

And, could BulkUpdate increase count? for example:
```sql
update [dbo].[table1]
set [count] = [count] + 1
where ...
```

**Comment by borisdj** [comment]
Not directly, BulkExtensions  are for EF so you need entities.

If you explicitly want pure sql like this you could just use
````
var db = context.Database;
db.ExecuteSqlCommand("update [table1] set [IsActive]=arg1 where [Id]=arg2 and [OrderId]=arg3"));
db.ExecuteSqlCommand("update [table1] set [count]=[count] + 1 where ..."));`
````
Otherwise you can achieve both with BulkUpdate in the following way:
````
var entityList1 = context.Table1.Where(a => a.Id == arg2 && a.OrderId == arg3);
context.BulkUpdate(entityList);
````
````
var entityList2 = context.Table1.Where(a => ...)
foreach(var entity in entityList2)
    entity.Count = entity.Count + 1;
context.BulkUpdate(entityList2);
````
Reading from Db is not bottleneck with EF and it is much faster then Insert/Update so it will not significantly affect performance.

**Comment by kexxxfeng** [comment]
Thx for you. I see.
