### ISSUE TITLE
BulkDeleteAsync() followed by BulkInsertAsync() failed

### ISSUE THREAD

**Issue by android8** [borisdj/EFCore.BulkExtensions#351]
In a ASP.Net CORE MVC app, I issued BulkDeleteAsync() then BulkInsertAsync() from the web application like so.  Thanks for your help.

            IList<TblUserAnswer> oldAnswersInDb = _repoAggregate.UserAnswer_Repository.FindByCondition(x => oldAnswerIDs.Contains(x.UserAnswerId)).ToList();

            //delete old answers
            _repoAggregate.UserAnswer_Repository.BulkDeleteAsync(oldAnswersInDb);

            //bulk insert newAnswers
            _repoAggregate.UserAnswer_Repository.BulkInsertAsync(theseTblUserAnswers);

The methods are declared in the another repository project as below.  
    
    public RepositoryBase(MyAppContext repositoryContext)
    {
      this.RepositoryContext = repositoryContext;
    }
    public async Task BulkDeleteAsync(IList<T> entityList)
    {
      await RepositoryContext.BulkDeleteAsync(entityList);
    }
    public async Task BulkInsertAsync(IList<T> entityList)
    {
      await RepositoryContext.BulkInsertAsync(entityList);
    }

The call ran without throwing exceptions, but nothing was changed in the table.   The Kestrel output window shows the following failure. 

    Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (194ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT TOP 0 T.[UserAnswerID] INTO [app].[tblUserAnswerTempe037abd2] FROM [app].[tblUserAnswer] AS T LEFT JOIN [app].[tblUserAnswer] AS Source ON 1 = 0;
 
The Visual Studio 2019 Diagnostic Tool shows "The connection does not support MultipleActiveResultSets" exception on BulkInsertAsync().  It also shows "'Invalid operation. The connection is closed.' exception in BulkDeleteAsync().

**Comment by borisdj** [comment]
Can you make a test where this would be reproducible.

**Comment by mkgn** [comment]
I thought to reopen this because I am getting the same error. I am on:
Asp.Net web app using .Net 5 & efcore with MS Sql Express 11.0

What I am trying to do is import some users to AspNetUsers table (which is from Identity). When seeding the database I create some users directly from dbContext. So we should be able to insert data to this table with this package as well (without relying on UserManager).

So I fill up my collection to a List<ApplicationUser> and just do;

             using (var transaction = dbContext.Database.BeginTransaction())
            {
                dbContext.BulkInsertOrUpdateAsync(dataToInsert);
                transaction.Commit();
            }

No errors are thrown and the SQL Profiler shows the attached trace. Basically it goes like below; 

Few : set xact_abort on;set nocount on; entries
Few select statement targeting the table that needs to insert the data
Another statement like below that shows a temporary table prepared for insert (i suppose?). Also i have remove some columns to keep it simple.

    SELECT TOP 0 T.[Id], T.[Zip] INTO [dbo].[AspNetUsersTempc0270710] FROM [dbo].[AspNetUsers] AS T LEFT JOIN [dbo].[AspNetUsers] AS Source ON 1 = 0;

and then another 

    select @@trancount; SET FMTONLY ON select * from [dbo].[AspNetUsersTempc0270710] SET FMTONLY OFF exec ..sp_tablecollations_100 N'[dbo].[AspNetUsersTempc0270710]'

And finally insert bulk statement like(again removed some columns);

    insert bulk [dbo].[AspNetUsersTempc0270710] ([Id] BigInt, [AccessFailedCount] Int, [UserName] NVarChar(256) COLLATE SQL_Latin1_General_CP1_CI_AS, [Zip] NVarChar(20) COLLATE SQL_Latin1_General_CP1_CI_AS)

As you see it refers to a temporary table, but doesn't really output anything about the AspNetUsers table to which the data should actually be inserted. 

So this goes without an error, then .commit() is also executed and shortly after that the exception pops up:

    "The connection does not support MultipleActiveResultSets"

If you can point me to few places where I should start troubleshooting I might be able to help if this is a bug.

[bulk-trace.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/6725038/bulk-trace.zip)

**Comment by borisdj** [comment]
It would be best if could write test to reproduce the issue.
Take a look at examples in the source code, Solution has additional Test project.

**Comment by MaceWindu** [comment]
both code examples lack `await` on async calls

**Comment by borisdj** [comment]
Yes, and Commit also CommitAsync so it should be:
```C#
using (var transaction = dbContext.Database.BeginTransaction())
{
  await dbContext.BulkInsertOrUpdateAsync(dataToInsert);
  await transaction.CommitAsync();
}
```

**Comment by mkgn** [comment]
doh.... That was the problem... I waste so much time looking at trace logs :) Thank you so much
