### ISSUE TITLE
Support for SQLLITE?

### ISSUE THREAD

**Issue by Zarkos69** [borisdj/EFCore.BulkExtensions#37]
Hello,

Is there any support for SQLLite, if not, is there a plan to do so in the future? and when?

Kind regards

**Comment by borisdj** [comment]
There is no support for SQLLite, and no future plan for it because SqlBulkCopy cannot use SQLLite as Db.
SqlBulkCopy is made only for SQL Server.
Here are some links about improving performance when using SQLLite:
[http://procbits.com/2009/09/08/sqlite-bulk-insert](http://procbits.com/2009/09/08/sqlite-bulk-insert)
[http://blog.quibb.org/2010/08/fast-bulk-inserts-into-sqlite/](http://blog.quibb.org/2010/08/fast-bulk-inserts-into-sqlite/)
[https://www.jokecamp.com/blog/make-your-sqlite-bulk-inserts-very-fast-in-c/](https://www.jokecamp.com/blog/make-your-sqlite-bulk-inserts-very-fast-in-c/)

**Comment by borisdj** [comment]
SQLite is now also supported, from version 2.6.0

**Comment by vde07010702** [comment]
I was looking for SqliteBulkCopy and found some source in the following link thanks to doughjoe77:
https://github.com/aspnet/Microsoft.Data.Sqlite/issues/289, which is now closed.
I had to fix the following issues, then it worked fine (a bit on the slow side). I would like to share my corrections:
- [] had to be added to column names, since special names like "Order" do not work with INSERT, so this would become "[Order]".
- For REAL numbers ',' had to be replaced by '.' since values like 0,1 (in my country representation) were inserted as "0","1" with one value too much.
- The string generated for the INSERT containes \r\n (CR LR) characters, presumably inserted by the StringBuilder. These had to be extracted.
