### ISSUE TITLE
Oracle Support

### ISSUE THREAD

**Issue by msadikkose** [borisdj/EFCore.BulkExtensions#375]
Hello,
Is there any plan to Oracle Support? 

Kind regards.

**Comment by arivera12** [comment]
I don't think this would be supported since the kind of operations this library offers are Sql Server specific classes that helps to do this. There is no straight forward way too support multiple database engines out of the box without taking in consideration the database engine specific implementations. Take note I am not the owner or contributor of this project but I think this will be the answer: No plans to support Oracle in the near future.

**Comment by borisdj** [comment]
I will just copy the comment:

> No plans to support Oracle in the near future.

**Comment by kl1mm** [comment]
So sad to here this:
> I will just copy the comment:
>>No plans to support Oracle in the near future.

The Oracle .NET Team added Support for BulkCopy-Operations in their Oracle.ManagedDataAccess and Oracle.ManagedDataAccess.Core libs.

I love EFCore.BulkExtensions, and I already use it in some projects because of the huge performance benefits when processing big data.

Unfortunately our new project is tied to Oracle in production, but we are still using sqlite in testing :)
It would be great if you could give us some insight on what would be needed to support Oracle or possibly other database. 

Thanks a lot,
mMilk

**Comment by borisdj** [comment]
Project currently works with SqlServer and Sqlite, next in plan is PostgreSql, so code is already segmented for multiple DB support.
Take a look at the source code in the regard.
A lot of methods, memory lists, and EF meta data is shared.
So main difference is Sql/Sqlite Adapter code and part of pure Sql syntax.

I haven't used Oracle so am not familiar with it.
Still you can fork the library try to add support.
