### ISSUE TITLE
Question: How to do Bulkread with joining tables

### ISSUE THREAD

**Issue by rdasgupta7141** [borisdj/EFCore.BulkExtensions#414]
I have say a employee table and a look up table called employeeType (say fulltime,partime)

How can I use bulk read against the employee table when the where clause is employeeTypeName?

**Comment by borisdj** [comment]
For BulkRead you need list of uniqe column values.
Take a look at [Read example](https://github.com/borisdj/EFCore.BulkExtensions#read-example) in the ReadMe.
Now that list can first be filtered with some FK.

**Comment by rdasgupta7141** [comment]
@borisdj : Thanks for prompt response. I did follow that example before I posted the question here. It works if I am reading it off just one table. But what I intend to is to read off the Employee table based on the LookUp table EmployeType Name (Full-time).
 I just have empployeeTypeID in the employee table. I did something like 

 employeeTypeNames.Select(a=> new Employee{ EmployeeType= new EmployeeType{Name=a.Name}}
var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { nameof(Employee.EmployeeType.Name) } };

It's not working for. Please advise.

**Comment by cristian-eriomenco** [comment]
I could not find the example useful as well. Any updates on this please?

**Comment by borisdj** [comment]
That's not what BulkRead is used for.
BulkRead is useful when there is external import, say list of mails, and then we need to get Users from Db with those mail.
If User table has 20 milion rows and imported list has 1 milion mails.
Since simple select would be slow in this case, BulkRead is much efficient, example:
```C#
// USE
var users = mails.Select(a => new User { Email= a }).ToList(); // creating list of Users with Email set
var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { "Email"} };
context.BulkRead(users , bulkConfig); // Data loaded from Db with other properties
```
When doing simple read from DB with some `Where` clause then simple `Select` if sufficient.
