### ISSUE TITLE
Insert operation. Npgsql.PostgresException: "23502: null value in column "id" violates not-null constraint"

### ISSUE THREAD

**Issue by EugeniZaplatin** [borisdj/EFCore.BulkExtensions#423]
Every entity in list has Id value, but I get exception:
![image](https://user-images.githubusercontent.com/11317749/98449488-98de0500-2166-11eb-833e-07267efc7cf4.png)

I am use EF Core 2.2

**Comment by borisdj** [comment]
Library does not currently support PostgreSQL.
Dupe https://github.com/borisdj/EFCore.BulkExtensions/issues/132

**Comment by mwpowellhtx** [comment]
Is this **_still_** an issue today? In our case we would like to land in a `JSON` column in the database, doing some `ValueConverter<ICollection<string>, string>` work to bridge the gap between model and database. Still no joy. I promise you model and mapping converter side of things, there is more than adequate `null` arity cross checking, so we do not think it can be that side of things; the issue is purely `pg` and whatever is directly atop that.
