### ISSUE TITLE
Stop duplicating records

### ISSUE THREAD

**Issue by timothydowd** [borisdj/EFCore.BulkExtensions#446]
Hello

I want to only add new records to a table in my db via a list that contains records that already exist in the db table and new records.  I am currently managing to add the new records but I am also unfortunately adding the old ones, meaning duplicates are made in the table.

I have a domain object called InstagramInsightDatum that looks like this and a table in my db to reflect it:

```
        public int InstagramInsightDatumId { get; set; }

        public int Value { get; private set; }

        public DateTime EndTime { get; private set; }

        public int InstagramInsightId { get; set; }

        public InstagramInsight InstagramInsight { get; set; }
```

I want to only add new InstagramInsightDatums to the db when they are unique.  I will never need to update these records, just add new ones.  At the moment my code looks like this: 

![image](https://user-images.githubusercontent.com/39065501/103439650-a24f8f00-4c36-11eb-9915-7c58e6cab3ab.png)

I've highlighted the line where i add these datums to the table where the duplicates are happening in red - here you can see I am making the bulkInsert with the InstagramInsightDatums, and setting the PropertiesToExclude to InstagramInsightDatumId (I am not 100% how this config is meant to work but I assumed this feature is to allow us to ignore certain properties when comparing data?) - as removing the PK from the properties should reveal any potential duplicates...  

Can anyone see why this isnt working?  Everytime i execute the above code it actually duplicates the whole table..

**Comment by borisdj** [comment]
If you want to use only  `BulkINSERT` then in that method should be sent only List with new ones. BulkRead can be used to first load existing ones and then omit those from the InsertList.

Other way would be to use entire initial list but to call method `BulkInsertOrUpdate`.
For that `BulkConfig` should be set with
`PropertiesToIncludeOnUpdate = new List<string> { nameof(InstagramInsightDatum.InstagramInsightDatumId ) }`
Since `InstagramInsightDatumId`  is Id it will be removed from Propertis for Update leaving it empty ann effectivly all for update will be skipped.
