### ISSUE TITLE
support for .NET framework 4.6.2

### ISSUE THREAD

**Issue by seenals** [borisdj/EFCore.BulkExtensions#45]
Will you releasing this package with support for 4.6.2 and 4.7?
That will be great.

**Comment by ardennext99** [comment]
I'm also waiting the 4.7 support. thanks a lot.
Great work

**Comment by borisdj** [comment]
It already is supported, as said in README:
'It (Library) is targeting NetStandard 2.0 so it can used on project targeting NetCore(2.0+) or NetFramework(4.6.1+).'

**Comment by ardennext99** [comment]
I’ tryed to install, but ite return this error.

 


Severity

Code

Description

Project

File

Line

Suppression State


Error

 

Could not install package 'EFCore.BulkExtensions 2.0.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

 

 

0

**Comment by borisdj** [comment]
What version of Visual Studio do you have, there was some [bug](https://github.com/dotnet/standard/issues/481) regarding this with VS 2015, so upgrade to VS 2017 if you don' have that version already.
Otherwise check your project, there might be some reference to older .Net version packages that could be creating this issue.

I have just made a test by creating New project: ASP .NET Core Web App, selected .Net Framework 4.7 as target and successfully added EFCoreBulk nuget, so it works just fine.
