### ISSUE TITLE
Getting Deadlock Issues while doing Bulk insert

### ISSUE THREAD

**Issue by srini1978** [borisdj/EFCore.BulkExtensions#46]
We are using the bulk insert package and in regular tests, the inserts go through fine but in load tests where multiple web jobs are trying to do bulk inserts, we are getting deadlocks. Any pointers or settings that you can tell us how to solve the issue

**Comment by borisdj** [comment]
That's a tricky issue, and the problem is in the SqlBulkCopy itself.

According to [How to increase performance of SqlBulkCopy](https://forums.asp.net/t/1731116.aspx+)
You could set TableLock (in BulkConfig.SqlBulkCopyOptions), then do test again and see if it helps.
You may also try setting [WithHoldlock](https://github.com/borisdj/EFCore.BulkExtensions/issues/41) to false (true is default) but I'm not sure that can solve this.

Secondly in previous link and these:
[MSDN: Deadlock when using sqlbulkcopy](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/932cd26c-53fc-49c0-b082-e7f5f05a9801)
[Importing Data in Parallel with TableLock](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2005/ms186341(v=sql.90))
it is said that removing Indexes (clustered one as well) from destination table should eliminate lock problems. However library currently does not have options that would remove Indexes and then restore then after import. Also it's questionable whether removing Indexes is ideal solution. But you test it by removing them manually just check if that is one of solutions.

If you want to dig further:
[enabling trace flags on the SQL Server and log the deadlock graph to the ErrorLog](https://www.sqlservercentral.com/Forums/Topic587595-386-1.aspx)
[SO: sqlbulkcopy-causing-deadlock](https://stackoverflow.com/questions/39124318/sqlbulkcopy-causing-deadlock)

More info:
[Q: SQL-Server-deadlocks](https://www.quora.com/How-do-I-resolve-a-SQL-Server-deadlocks-issue-Two-threads-writing-to-same-table-at-a-time-and-causing-issue-How-does-it-affect-with-clustered-and-nonclustered-indexes)
[ADev: sqlbulkcopy-to-sql-server](https://www.adathedev.co.uk/2011/01/sqlbulkcopy-to-sql-server-in-parallel.html)
[WP: SqlBulkCopy-Performance](https://www.sqlbi.com/wp-content/uploads/SqlBulkCopy-Performance-1.0.pdf)

**Comment by domainmurat** [comment]
I am thinking apply the object locking solution that you mentioned . Do you think object locking could cause another issues ? @borisdj

**Comment by Tyler-V** [comment]
Old thread but relevant to me now @borisdj 

I have a solution that processes concurrent service bus messages in parallel through function apps resulting in the database getting hammered and an occasional deadlock.

Setting `WithHoldlock` to `false` does resolve my issue - are there any ramifications to setting this false if I am using `BulkInsertAsync` on new rows of data every time?
