### ISSUE TITLE
Concurrency check is missing in Updates

### ISSUE THREAD

**Issue by DevInstinct** [borisdj/EFCore.BulkExtensions#469]
This is a duplicate of https://github.com/borisdj/EFCore.BulkExtensions/issues/209, which has been unfortunately closed.

Entity Framework generates a WHERE close on updates to check concurrent updates for each entity that has a concurrency token (timestamp). The bulk updates don't generate those WHERE clauses and skip EF concurrency checks.

Any plan to add support for concurrency checks?

**Comment by borisdj** [comment]
Will consider it.
So when concurrency conflict is found the operation should abort?

**Comment by DevInstinct** [comment]
My suggestion would be that the operation should throw a concurrency exception.

**Comment by borisdj** [comment]
Support added with latest version 3.4.7+.
For _BulkUpdate_ set
`bulkConfig = new BulkConfig { SetOutputIdentity = true, DoNotUpdateIfTimeStampChanged = true };`
IT works in a way that those rows wiht concurrency conflict meaning TimeStamp column is changed since read, will not be update and their entites will be loaded into _BulkConfig_ in **_TimeStampInfo_** object with properties:
`{ int NumberOfSkippedForUpdate, List<object> EntitiesOutput }`
After reading them, depending on our need, we can either leave them skipped, update them again, throw exception or even rollback entire Update.
Example in the Test:
https://github.com/borisdj/EFCore.BulkExtensions/blob/f86762094f10381dfbd047aaa9bc2145f4fc93d7/EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs#L57-L103

**Comment by defunky** [comment]
@borisdj I can't seem to get this to work, TimeStampInfo seems to always be null. I've defined the RowVersion as RowVersion type in the table? Does the library support optimistic locking via ConcurrencyCheck attribute as well?

**Comment by oresttkachukd** [comment]
Tried both, always receive TimeStampInfo to be null:
-  type: "timestamp", rowVersion: true, nullable: false
-  type: "rowversion", rowVersion: true, nullable: false

**Comment by oresttkachukd** [comment]
@defunky in case it is still valid - adding SetOutputIdentity = true fixes the issue
