### ISSUE TITLE
Merge Matching on Null

### ISSUE THREAD

**Issue by shanesrus** [borisdj/EFCore.BulkExtensions#48]
I'm trying to **BulkInsertOrUpdate** with the defined list of **UpdateByProperties**. The only way I'm able to get it to update instead of insert is when the **UpdateByProperties** list contains all non-null values for a row. So for example, a row of data consists of _Field1_, _Field2_, _Value_, with _Field1_ and _Field2_ as **UpdateByProperties**. If a row of data that exists currently has _Field1_ = 'a' and _Field2_ = 'b' and the new data matches this, it will correctly update _Value_. But if _FieldB_ is null in both the existing row and the new row, a second row gets inserted.

Is there a property I should be using to get around this or is there a way that I can get nulls to be matched?

**Comment by borisdj** [comment]
The problem here is that Sql does not compare Null values:
`AND T.[Name] = S.[Name]`
is False even when both are null.
But this could be changed to something like:
`AND (T.[Name] = S.[Name] OR (T.[Name] IS NULL AND  S.[Name] IS NULL))`
Then it should work. I will see to fix this soon.

In the meanwhile you can make a workaround by making 2 updates, where first will have list of those that do not have Null in that column which will be included in **UpdateByProperties**, while second Update will have only those with Null in that column and that operation will Not have this Property in **UpdateByProperties**.

**Comment by borisdj** [comment]
UpdateByProperties Nullable support added in version 2.0.9

**Comment by borisdj** [comment]
UPDATE: 2.0.9 has bug NullReference Exception.
Upgrade to EF Core 2.1 and use Nuget 2.1.0
