### ISSUE TITLE
Odd behavior when rounding datetime

### ISSUE THREAD

**Issue by DannyBoyNg** [borisdj/EFCore.BulkExtensions#510]
I noticed some odd behavior when bulk inserting. Lets say I have a table with a column that is a DateTime2(3) with precision 3.

When inserting the following datetime from code "2021-04-01 09:37:10.6097403". The result in Sql Server is "2021-04-01 09:37:10.609".

When inserting the same datetime with Entity Framework the result is "2021-04-01 09:37:10.610".

So it seems like Entity Framework is rounding correctly and bulkinsert is just truncating. I would prefer that bulkinserts behavior aligns more with what Entity Framework does.

Maybe there is an option I can use to round instead of truncate? Please help.

**Comment by DannyBoyNg** [comment]
To me, insert performance is much more important than rounding. So only implement this feature if it doesn't negatively impact the performance.

**Comment by borisdj** [comment]
Strange behaviour, but I can cofirm the issue.
It seems that this is due to the implmentation of SqlBulkCopy and I don't a way to change it.
So the solution, as you already implied, would be to round it in memory before sending to Db.

Option 1. (only Floors to Milisecond):
```C#
foreach (var entity in entityList)
{
  var dt = entity.DateTime;
  entity.DateTime  = new DateTime(dt.Year, dt.Month, dt.Day, dt.Hour, dt.Minute, dt.Second, dt.Millisecond);
}
```

Option 2.
It you want precise Round then you need to read Micro and Nano second in order to do Rounding on Milisecond.
However DateTime type in C# does not have directly exposed that precision, so it needs to be read it from Ticks or String and do the rounding.
2.a) form String
```C#
var dateFormat = "yyyy-MM-dd HH:mm:ss.fffffff";
foreach (var entity in entityList)
{
  var dt = entity.DateTime;
  var millisecondString = dt.ToString(dateFormat).Substring(20, 7);
  var millisecond = (int)Math.Round(decimal.Parse(millisecondString) / 10000, 0);
  entity.DateTime  = new DateTime(dt.Year, dt.Month, dt.Day, dt.Hour, dt.Minute, dt.Second, millisecond);
}
```
2.b) using Tick
[c-sharp-time-in-microseconds](https://stackoverflow.com/questions/1206367/c-sharp-time-in-microseconds)

**Comment by DannyBoyNg** [comment]
Thank you for your comment. I'll close this issue now.

**Comment by borisdj** [comment]
Using Ticks is better option so I've update the previous comment.

**Comment by borisdj** [comment]
With latest v5.0.2 (that is now for EF Core 5) automatic rounding is integrated into the library.
Just need to set `BulkConfig.DateTime2PrecisionForceRound = true`

**Comment by DannyBoyNg** [comment]
Oh wow. Thank you so much Borisdj!
