### ISSUE TITLE
Q: BulkRead  - How To?

### ISSUE THREAD

**Issue by bodeg** [borisdj/EFCore.BulkExtensions#513]
I couldn't realize how do I  BulkRead the following

`var items = _dbContext.Students.Where(x => x.Age < 3).ToList(); `

I appreciate any help. Thanks

**Comment by borisdj** [comment]
_BulkRead_ can not used for that, nor would it have purpose since simple read from Db like this is not slow.
There is more info in the ReadMe, at the bottom, about when an how it can be used.
Essentially you need list of some unique properties which will be loaded with entities, and there it is used instead of WHERE-IN that would be slow for large lists.
