### ISSUE TITLE
Cannot drop the table

### ISSUE THREAD

**Issue by BlowaXD** [borisdj/EFCore.BulkExtensions#52]
Hello,

I encoutered an issue using EFCore BulkExtensions.
The db user is set as db_owner on the related database

![image](https://user-images.githubusercontent.com/16936368/41559576-b68219a2-7344-11e8-8dc0-c9ef2ad34995.png)
Does anyone has any clue on that ?

![image](https://user-images.githubusercontent.com/16936368/41559615-ce239bee-7344-11e8-927f-7aaa5d149711.png)

Code I use for that :
![image](https://user-images.githubusercontent.com/16936368/41559665-f87231d0-7344-11e8-90e3-d41fd111ae02.png)

If you need any information, do not hesitate.

PS : It's not about rights, I can delete a table with Navicat / SQL Management Studio / MSSQL Tools with the same credentials

Btw, thanks for your awesome work, it's saving my life <3

**Comment by BlowaXD** [comment]
It happens when I'm updating data from previously recovered entities.

I'll try the sample asap (hope tomorrow)

**Comment by BlowaXD** [comment]
Another thing, I'm using MSSQL for Linux, on Docker
https://hub.docker.com/r/microsoft/mssql-server-linux/ 
latest release

**Comment by borisdj** [comment]
If you are doing only Update then use just BulkUpdate, no need for BulkInsertOrUpdate if you don't have new entities.
Secondly UseTempDb is False by default so no need for explicitly setting it to false.
Also if you have only one Bulk operation in method then explicit transaction is redundant.

**Comment by borisdj** [comment]
So far I have only tested it with MSSQL on Win 10.

**Comment by BlowaXD** [comment]
Hey !

I've got some more informations that I've found !
![image](https://user-images.githubusercontent.com/16936368/41625123-ff35e420-7417-11e8-8130-bfa649169417.png)

The exception thrown is not correct (at least, not deep enough), it looks like when a merge fails, the table is automatically dropped (A way to add a custom exception to handle it correctly ?)

The issue does not come from you but it can improve your awesome project !

:)

**Comment by borisdj** [comment]
Great you solved it.
I have just made a test for this situation(InsertOrUpdate-ing with 2 row that have same Id in Source) and it gives me correct error:

> Test failed
> Message: _System.Data.SqlClient.SqlException 
_The MERGE statement attempted to UPDATE or DELETE the same row more than once. This happens when a target row matches more than one source row. A MERGE statement cannot UPDATE/DELETE the same row of the target table multiple times. Refine the ON clause to ensure a target row matches at most one source row, or use the GROUP BY clause to group the source rows._

I'm not sure why you first got _Can Not Drop the Table_ error.
I have also checked and MsSQL does not Drop custom Temp tables on its own.
Maybe it could be something specific for MsSQL on Linux but I doubt.

**Comment by borisdj** [comment]
You can make a test with these scripts.
First create EFCoreBulk Test DB:
[EFCoreBulkTestDB.sql](https://drive.google.com/file/d/1muCRNz5IZd06hP0g4FG4S35a_W6dmpIQ)
Then Run this Sql script.
[EFCoreBulkTestSQL.sql](https://drive.google.com/file/d/1Zwm9DTHrnGPd_O7HCHEvqobox4XFJa8B)
It should give you correct error and then refresh it and check it Temp table remaind in DB.

**Comment by BlowaXD** [comment]
Sorry for the late reply, I was busy, i'll try it as soon as I arrive home (can't try it with my actual env)
