### ISSUE TITLE
Exception "Value cannot be null. (Parameter 'method')"

### ISSUE THREAD

**Issue by kaneno1** [borisdj/EFCore.BulkExtensions#538]
I am not sure if this is bug, but anything what is using FastProperty.cs and InitializeSet() return this error if entity class does not have  setter. In my case using truncate throw error. Example:
 public string Id { get; } will throw error 
 public string Id { get; set; } will not.

this is related to 
 var setter = Property.GetSetMethod(true) ?? Property.DeclaringType.GetProperty(Property.Name).GetSetMethod(true); // when Prop from parent it requires DeclaringType
 SetDelegate = Expression.Lambda<Action<object, object>>(Expression.Call(instanceCast, setter, valueCast), new ParameterExpression[] { instance, value }).Compile();

**Comment by borisdj** [comment]
This could be fixed with:
`if(setter != null) SetDelegate = Expression...`
That will leave this column with _Null_ in Db, so it could work if that is desired outcome which seems to be based on definition:
`public string Id { get; }`
But if defined with some other custom value, Bulk would still leave it Null in Db, so that case would not behave like EF SaveChanges does, example:
`public string Id { get; } = "xyz";`

**Comment by borisdj** [comment]
Fixed with v5.1.3
