### ISSUE TITLE
Unable to use library for tables with only key columns. "operation can not have zero columns to update."

### ISSUE THREAD

**Issue by theb0rg** [borisdj/EFCore.BulkExtensions#543]
I am getting "'BulkInsertOrUpdate' operation can not have zero columns to update.".

I have traced it to the recent commit from below
[Commit](https://github.com/borisdj/EFCore.BulkExtensions/commit/0bd51b505e1ad38b59f872664a702de6c892e7c1)

In my case it seems to affect tables that only contain key columns? 
Why has this become an illegal operation?

**Comment by borisdj** [comment]
If you are using pure Update then the operation can update anything so no purpose to call it.
Or you are using InsertOrUpdate and want to result to be only to insert new ones?

**Comment by maximtmartin** [comment]
I do get the same error when using "InsertOrUpdate" for a table with only a composite primary key.

Since the table only exists of a primary key the only "action" we will be doing is an insert. The thing is: when using "Insert" we will get PRIMARY_KEY collisions.

The only thing we can do check which keys already exist in the table and remove them from the insert collection?

**Comment by borisdj** [comment]
Fixed with v5.1.4

**Comment by theb0rg** [comment]
@borisdj Yes, i want a upsert operation with InsertOrUpdate that only inserts new ones. (since insert fails when the row exist).

**Comment by borisdj** [comment]
That's how it works now.
