### ISSUE TITLE
please switch to `Microsoft.EntityFrameworkCore.Sqlite.Core`

### ISSUE THREAD

**Issue by springy76** [borisdj/EFCore.BulkExtensions#544]
`Microsoft.EntityFrameworkCore.Sqlite` (without `Core`) is only a meta package which additionally references conrete SQLite implementations - there should be no need to.

**Comment by borisdj** [comment]
Changed with v5.1.3

**Comment by palhal** [comment]
Shouldn't this be documented somewhere? After upgrading from 5.1.2:

> System.Exception: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().

Turns out I had to add _SQLitePCLRaw.bundle_winsqlite3_ as a package reference as seen in commit 30e93d51b0547fc2c731affd01cdada08f7bfad7.
Also, it seems to work fine without calling SQLitePCL.Batteries.Init(). What is the recommendation here?

**Comment by borisdj** [comment]
Added note to ReadMe.
As for the call `SQLitePCL.Batteries.Init()` it is required when running app for the first time, afterwards seems to work even without it, but better to keep it to be safe.

**Comment by borisdj** [comment]
_SQLitePCLRaw.bundle_winsqlite3_ is now replaced with _SQLitePCLRaw.bundle_e_sqlite3_ so that the SQLite tests can pass also on Linux and macOS.
