### ISSUE TITLE
Change IList<T> to IEnumerable<T>

### ISSUE THREAD

**Issue by nh43de** [borisdj/EFCore.BulkExtensions#549]
For large data sets that are not Lists.. eg. from a CSV file, materializing to a list is not practical.

The change would involve swapping out IList in favor of IEnumerable where possible. (Most places in the code I saw only enumerate the IList and do not actually use IList members).

If you're open to making this change let me know and I can submit a pull request.

Nathan

**Comment by borisdj** [comment]
There have already been PR for this that was merged but later reverted because List was required for  _UpdateEntitiesIdentity(SetOutputIdentity)_.
https://github.com/borisdj/EFCore.BulkExtensions/issues/147

Maybe to consider supporting both, you can try making a change in that direction.
Simple solution could be just to add duplicate Extension methods, although I don't like going far away from DRY, and then see where can flow of functions be merged, similary as is done for BulkConfig/Action and Async/Sync.

**Comment by borisdj** [comment]
Bulk methods are now receiving **IEnumerable**.
