### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by RemMai** [borisdj/EFCore.BulkExtensions#553]
Can MySQL be supported?

MySQL 8.0.23

.net 5

Thanks!!!!!

能支持MySQL吗？

**Comment by borisdj** [comment]
Not soon, but will consider it in the long run.

**Comment by OronDF343** [comment]
From my experience emulating `SqlBulkCopy` on MySQL, I found that the closest alternative is `MySqlBulkLoader` (from the official driver `MySql.Data`).
This means saving the data to a CSV (or DSV) file and doing something like this:
```
var msbl = new MySqlBulkLoader(connection);
msbl.TableName = tableName;
msbl.FileName = tempCsvFile;
msbl.FieldTerminator = ",";
msbl.FieldQuotationCharacter = '"';
msbl.LineTerminator = Environment.NewLine;
msbl.Local = true;
msbl.CharacterSet = "utf8";
msbl.Load();
```
This executes the `LOAD DATA LOCAL INFILE` command, which requires that the `local_infile` system variable is enabled on the server (it's disabled by default due to security concerns. See [here](https://dev.mysql.com/doc/refman/8.0/en/load-data-local-security.html)).

I have tested this with MariaDB, should be the same in official MySQL.

**Comment by charleypeng** [comment]
this feature is quite needed because sqlserver is so complecated for use in a linux  VPS, and sqlite lack of efficiency, mariadb is a good choice so if bulk extension support it will be so great.

**Comment by borisdj** [comment]
For usage in Linux environment another good option is PostgreSQL for which support was just added with latest version of BulkExtensions.

**Comment by NJadeRabbit** [comment]
I want to use mysql. My business is based on MySQL. Can you help me?

**Comment by borisdj** [comment]
Adding support for another server is a big feature so still no timeframe for it.
I'll write here any updates on progress.

**Comment by cnkerry** [comment]
anxious

**Comment by saeidbabaei-dev** [comment]
I created a pull request : https://github.com/borisdj/EFCore.BulkExtensions/pull/881

**Comment by saeidbabaei-dev** [comment]
I created a pull request : #889

**Comment by borisdj** [comment]
NuGet 6.5.6 published, all Bulk ops supported.
Kudos to @saeidbabaei-dev
