### ISSUE TITLE
Violation of Primary Key Constraint

### ISSUE THREAD

**Issue by DaleyKD** [borisdj/EFCore.BulkExtensions#554]
I'm trying to use the `BulkInsertOrUpdateAsync` function.  My `Item` class has `ID` which is of type `Guid` and is generated by the database.

The following sample throws the exception:
>> Violation of PRIMARY KEY constraint 'PK_Items'. Cannot insert duplicate key in object 'dbo.Items'. The duplicate key value is (00000000-0000-0000-0000-000000000000).
The statement has been terminated.

How do I set the options so that it will let the database generate the identity?  (_I've tried to read your documentation, but it doesn't fully make sense to me, especially the `UpdateByProperties` and `PropertiesToIncludeOnCompare`, etc.  I'm sorry.)_

``` C#
private async Task TestFunction(IEnumerable<IListItem> items)
{
    var upsertEntities = new List<Item>();

    foreach (var listItem in items)
    {
        var existingItem = await _ctx.Items.AsQueryable().SingleOrDefault(i => i.ID == listItem.Id);
        if (existingItem != null)
        {
            existingItem.MyField = "new ID";
            existingItem.MyUrl = "new value";

            upsertEntities.Add(existingItem);
        }
        else
        {
            upsertEntities.Add(new Item()
            {
                MyField = "first ID",
                MyUrl = "first URL"
            });
        }
    }

    await _ctx.BulkInsertOrUpdateAsync(upsertEntities, o =>
    {
        o.SetOutputIdentity = true;
        o.UpdateByProperties = new List<string> { nameof(Item.ID) };
    });
}
```

EFCore.BulkExtensions: v5.2.1

**Comment by borisdj** [comment]
NonIdentity PK with DbGeneration behaves like a column with Default value, and it's implementation is specific.
Because of that when doing InsertOrUpdate it was not feasible to have in same list simultaneously both entities groups With and Without default values. There is a comment about this in code:
https://github.com/borisdj/EFCore.BulkExtensions/blob/22433dcb8925c130681654724e8302bc05e8ea17/EFCore.BulkExtensions/TableInfo.cs#L217
Now a change was made in that segment with regard to PK so your situation is fixed, published nuget 5.2.2.
