### ISSUE TITLE
BulkInsertOrUpdate StatsInfo.StatsNumberInserted Not Accurate

### ISSUE THREAD

**Issue by DaleyKD** [borisdj/EFCore.BulkExtensions#555]
In my preceding issue #554 , using the same code, but also setting `CalculateStats = true`, The `StatsNumberInserted` isn't fully accurate.  No actual items were `INSERT`ed.  Some may be `UPDATE`d, but zero is truly the answer for number that were actually put into the table.

Looking here, I see that we're just subtracting the number updated and the number deleted from the total number. 
 Is there a way to actually truly calculate what was inserted?
https://github.com/borisdj/EFCore.BulkExtensions/blob/22433dcb8925c130681654724e8302bc05e8ea17/EFCore.BulkExtensions/TableInfo.cs#L831

Thank you very much for this helpful library!

**Comment by borisdj** [comment]
If in the list you have Items with Guid Id and some of those have value Guid.Empty then those are the ones that will be inserted, so you should even know number of them in advance.
Otherwise if all have value other then empty but some do not exist in database then calculation should be correct:
`StatsNumberInserted = totallNumber - numberUpdated - numberDeleted`
_Example 1. out of 1000 in list, 200 do not exist in Db then:_
StatsNumberInserted = 1000 - 200 - 0 = 800
Example 2. out of 1000 in list, all exist in Db then:
__StatsNumberInserted = 1000 - 1000 - 0 = 0_
