### ISSUE TITLE
Cannot drop the table 'nameTable, because it does not exist or you do not have permission.

### ISSUE THREAD

**Issue by dasuma** [borisdj/EFCore.BulkExtensions#58]
i have this problem when i send to save 

Cannot drop the table 'dbo.nameTableTempf21dbf8f', because it does not exist or you do not have permission. 
i supose that is the error in my conectiongstring?
on the other hands my save is very slow is aprox seven minutes.

`   _context.Database.SetCommandTimeout(360);
                //listTemp = listTemp.OrderBy(T => T.Id).ToList();
                // _context.Database.SetCommandTimeout(0);

                using (var transaction = _context.Database.BeginTransaction())
                {
                    //_context.BulkInsert(listTemp, new BulkConfig {  SetOutputIdentity = true, BatchSize = 4000,NotifyAfter=240 });
                    _context.BulkInsert(listTemp, new BulkConfig { SetOutputIdentity = true, NotifyAfter = 360 });

                    transaction.Commit();
                }`

**Comment by borisdj** [comment]
This could be problem with permissions for DbUser used for connection in ConnString.
Or there is some error and then TempTable, that is used when SetOutputIdentity is set, can not be deleted.
Try setting UseTempDB to True and see what happens then.
How many items are there in your listTemp?
You could try to debug it more by adding source of library into project instead of Nuget.
