### ISSUE TITLE
"The given ColumnMapping does not match up with any column in the source or destination."

### ISSUE THREAD

**Issue by CodySchrank** [borisdj/EFCore.BulkExtensions#63]
This is not a bug but I feel like this message could be improved.  

If its possible could the mismatched columns be outputted?  I spent too long looking for a mismatched case when there was 1 column that didn't exist because a migration was created but the database was never updated.

**Comment by borisdj** [comment]
I don't see why it should take too long to find difference between columns of one table compared to one Entity.
Still I think this could be added.
That exception is being thrown on `sqlBulkCopy.WriteToServer(reader);` but it gives no more info so specific column could not be read from there.
What could be done is that additional function be added into `catch` segment which will check what column is missing. For this `CreateTableCopy` could be used since that function will return specific info like: 

> Invalid column name 'MissingColumnName'.

I will see to implement it with next version.

**Comment by CodySchrank** [comment]
Awesome thanks!  I agree its not a super big deal but when the table has 50+ columns and I'm not even aware that a migration was created (I didn't do it) then this could be very helpful again in the future.

**Comment by borisdj** [comment]
Improvement added with Nuget 2.1.8

**Comment by SimplerSoftware** [comment]
I just ran into this issue and found that there was a fix for it... which is great!  However, I updated the package and now I don't get any error, but it also doesn't actually insert any records into the table.  Any thoughts on this?

**Comment by SimplerSoftware** [comment]
After investigating, there were some columns that did not have the same case... but I was anticipating that I would still receive an error, just a more friendly one that would let me know which column/s were the offenders.  Is that not the case?

**Comment by borisdj** [comment]
Try now with 2.1.9 version.

**Comment by SimplerSoftware** [comment]
@borisdj -  I updated to 2.1.9 and am getting the exception now (as expected), but I was under the impression that the enhancement talked about here was going to tell me which column/s are the offenders.  Did I misunderstand something?

**Comment by borisdj** [comment]
It seems that you have some different situation where specific exception in not being catch.
Write more info on how to reproduce it and try debugging with library source.
