### ISSUE TITLE
Not working with EntityFramework Core InMemory

### ISSUE THREAD

**Issue by martonx** [borisdj/EFCore.BulkExtensions#657]
BulkInsert is working fine with EFCore SqlServer.
But when I want to test my methods with EfCore InMemory I get this error:

System.InvalidOperationException : Relational-specific methods can only be used when the context is using a relational database provider.

Please fix this error. I know EFCore InMemory is not a real Relational DB, but in this case BulkExtensions should fallback to other method. As now bulk insert code is untestable and false negative.

**Comment by borisdj** [comment]
This behaviour is documented in ReadMe:

> Bulk Tests can not have UseInMemoryDb because InMemoryProvider does not support Relational-specific methods.

Will consider the fallback options.
At the moment for Tests you could try using Test SqlServer or Sqlite.

**Comment by borisdj** [comment]
After some investigation, fallback is not a real option.
As stated here:
https://docs.microsoft.com/en-us/ef/core/testing/
> Approach 3: The EF Core in-memory database
> * EF Core comes with an in-memory database that we use for internal testing of EF Core itself. This database is in general not suitable for testing applications that use EF Core. Specifically:
> * It is not a relational database.
> * It doesn't support transactions.
> * It cannot run raw SQL queries.
> * It is not optimized for performance.

Since all of these things are used in BulkExtensions, you could only not use bulk for tests with InMemory (put 'if else' code).
But generally speaking for testing methods that have Bulk calls better practice would be to use some db, either SqlServer Developer or Express, or LocalDb, or even Sqlite.
