### ISSUE TITLE
Return data after Bulk Insert not coming in same Sequence as of Database

### ISSUE THREAD

**Issue by RusheeMahorkar** [borisdj/EFCore.BulkExtensions#70]
I have the GenericEntityRepository in that I have -
public virtual void BulkAdd(IEnumerable<T> BulkData) { _context.BulkInsert<T>(BulkData.ToList(), new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true }); 
_context.SaveChanges(); }

Call from business layer to repository -
ProjectRepo.BulkAdd(Tasks.AsEnumerable()); rd.DataToSend = Tasks;

I need to send the list data list back with id (Primary key)

Currently id is coming after the commit are in Ascending Sequence as of the BulkData Which Is I am expecting, But In database the rows are created with id Descending order. Primary Key Id are coming correctly in return type but in database its coming Descending order.

TaskId is auto incremented field in database.

If I do PreserveInsertOrder  = false output is coming correctly as accepted. But the id is coming 0. 

![bulkinsertissue](https://user-images.githubusercontent.com/11297620/44525777-ac286580-a6ff-11e8-9893-b14001d0d7e0.png)

**Comment by RusheeMahorkar** [comment]
TaskId is auto incremented field in database.

**Comment by borisdj** [comment]
IF you want Db to insert data based on order in your list then you need to set Id in that order your BulkData.ToList() before you send it to BulkInsert method.
It is explain in the README:

> **PreserveInsertOrder** makes sure that entites are inserted to Db as they are ordered in entitiesList.
However for this to work Id column needs to be set for the proper order.
For example if table already has rows, let's say it has 1000 rows with Id-s (1:1000), and we now want to add 300 more.
Since Id-s are generated in Db we could not set them, they would all be 0 (int default) in list.
But if we want to keep the order as they are ordered in list then those Id-s should be set say 1 to 300.
Here single Id value itself doesn't matter, db will change it to (1001:1300), what matters is their mutual relationship for sorting.

So in your example you need to set taskId(s) to values 1-to-N before you send that list into BulkAdd, or you can give them values inside that method like:
```
var list = BulkData.ToList();
int i = 1;
foreach (var item in list)
{
  item.taskId = i++;
}
_context.BulkInsert(list , new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true });
```

**Comment by RusheeMahorkar** [comment]
tried adding your code but there is an error coming, as it is the Primary key and auto increment field in database. 
Error - 
`Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index`

**Comment by borisdj** [comment]
One thing I forgot to mention is that Id for order has to be one that does not exist already in Db, as is explained in README:

> When using PreserveInsertOrder with BulkInsertOrUpdate method, Id value does matter for those that will be updated.
If we need to sort those for insert and not have conflict with existing Id-s, there are 2 ways:
One is set Id to really high values, order of magnitude 10^10, and another even better setting them to negative values.
So if we have list of 8000, say 3000 for update (they keep the real Id) and 5000 for insert then Id-s could be (-5000:-1).

But this rule apply not only to BulkInsertOrUpdate but also to BulkInsert.
So 'i' counter has to be negative, example:
`int i = -list.Count();

**Comment by fsudaman** [comment]
I just experienced this same issue and implemented the above to resolve the issue. Could the framework implement this when it knows that PreserveInsertOrder is set to true?

**Comment by borisdj** [comment]
It is explained in the README how to use methods with **PreserveInsertOrder**:

> **PreserveInsertOrder** makes sure that entites are inserted to Db as they are ordered in entitiesList.
However for this to work Id column needs to be set for the proper order.
For example if table already has rows, let's say it has 1000 rows with Id-s (1:1000), and we now want to add 300 more.
Since Id-s are generated in Db we could not set them, they would all be 0 (int default) in list.
But if we want to keep the order as they are ordered in list then those Id-s should be set say 1 to 300.
Here single Id value itself doesn't matter, db will change it to (1001:1300), what matters is their mutual relationship for sorting.

There is not much that can additionally be done in the library itself because since method is `BulkInsertOrUpdate` some row do need to have existing Id-s(part of list for update) and other must not existing have Id-s but should have some for their mutual order.
Setting these Id-s to proper value is responsibility of the caller of Bulk method.
Really high number could work there but for me it more practical to use negative values, since there is no chance for conflict and you can directly see how many there are.
