### ISSUE TITLE
Not yet supported MySql?

### ISSUE THREAD

**Issue by Mcgrady2009** [borisdj/EFCore.BulkExtensions#71]
Unable to cast object of type 'MySql.Data.MySqlClient.MySqlTransaction' to type 'System.Data.SqlClient.SqlTransaction'

**Comment by borisdj** [comment]
MySql is not supported, and no plans for it in the near future.

**Comment by Mcgrady2009** [comment]
Thank you, SqlServer has SqlBulkCopy implementation, MySql does not seem to be similar

**Comment by borisdj** [comment]
That's the case.

**Comment by salvador-guerrero** [comment]
A few years ago i handled bulk insertions to MySQL by exporting my data to a .csv file and importing it with [LOAD DATA INFILE](https://dev.mysql.com/doc/refman/8.0/en/load-data.html)

**Comment by gphadke-webuy** [comment]
Hi @borisdj, I was trying to use BatchDelete in MySQL and came across the below issue. 
An exception of type 'System.ArgumentOutOfRangeException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Length cannot be less than zero.'
   at System.String.Substring(Int32 startIndex, Int32 length)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql[T](IQueryable`1 query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.BatchUtil.GetSqlDelete[T](IQueryable`1 query, DbContext context)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDelete[T](IQueryable`1 query)

Can you please confirm if this is because there is no support for MySQL...?

**Comment by borisdj** [comment]
Yes, MySql is not supported.
At the moment only SqlServer and SQLite are.

**Comment by gphadke-webuy** [comment]
> Yes, MySql is not supported.
> At the moment only SqlServer and as of recently SQLite are.

Thanks for the prompt reply...:)

**Comment by borisdj** [comment]
MySQL support is now added.
