### ISSUE TITLE
Memory leak in EF Query cache caused by UpdateOutputIdentity

### ISSUE THREAD

**Issue by JanEggers** [borisdj/EFCore.BulkExtensions#73]
Im assuming this is the source of evil:

https://github.com/borisdj/EFCore.BulkExtensions/blob/39162d1719bfeede29b4d50b521750d421a422f9/EFCore.BulkExtensions/TableInfo.cs#L267-L277

im still investigating what is the issue

**Comment by JanEggers** [comment]
EF core tries to cache this query resulting in a memory leak in the query cache. I dont know if that is your fault or EF so I Will open an issue there aswell.

**Comment by borisdj** [comment]
I will look into it.

**Comment by borisdj** [comment]
How do you reproduce the leak?

**Comment by JanEggers** [comment]
you can use your unittests

add this:

context.BulkInsertOrUpdate(entities, new BulkConfig() { SetOutputIdentity = true}, (a) => WriteProgress(a));
                    
                    var compiledQueryCache = ((Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache)context.GetService<Microsoft.EntityFrameworkCore.Query.Internal.ICompiledQueryCache>());
                    var memoryCache = ((MemoryCache)typeof(Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache).GetTypeInfo().GetField("_memoryCache", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(compiledQueryCache));



                    Assert.Equal(0, memoryCache.Count);

**Comment by JanEggers** [comment]
there are queries in there you use in the testcode to eliminate them from the result use EF.CompileQuery instead of using querying directly. if these are eliminated you only have a query in the cache from the code I posted above.

**Comment by borisdj** [comment]
For start try adding `.AsNoTracking()`
`var query = context.Set<T>().FromSql(q).AsNoTracking();`
And check if there is any change.

**Comment by JanEggers** [comment]
that wont make a difference AsNoTracking is to track entities the leak is in the query cache. so just by executing FromSql with different temp tables it creates a new entry in a query cache

**Comment by JanEggers** [comment]
the EF team confirmed that FromSql with dynmic sql causes a memory leak. I will investigate alternatives

**Comment by borisdj** [comment]
1 Q.
In method UpdateOutputIdentity you have removed code part ToList(),
while in UpdateOutputIdentityAsync you removed .ToListAsync() but then added .ToList() at the end.
I think this should be consistent so I would remove .ToList() from Async version?

**Comment by JanEggers** [comment]
thx

**Comment by borisdj** [comment]
I have found one situation which throws Exception because of CompiledQuery.
When calling BulkInsertOrUpdateAsync() with BulkConfig.SetOutputIdentity = True.
Non Async method BulkInsertOrUpdate work fine and even Async without SetOutputIdentity i OK.
But when both used it throws:

> Message: System.ArgumentException : Expression of type 'System.Collections.Generic.IAsyncEnumerable`1[EFCore.BulkExtensions.Tests.Item]' cannot be used for return type 'System.Collections.Generic.IAsyncEnumerable`1[System.Collections.Generic.IEnumerable`1[EFCore.BulkExtensions.Tests.Item]]'

To reproduce it download repository code from this point (when your pull request was merged):
[https://github.com/borisdj/EFCore.BulkExtensions/tree/6d4a184ac2dc0d1322d7d02ef6fa30354154bd2f](https://github.com/borisdj/EFCore.BulkExtensions/tree/6d4a184ac2dc0d1322d7d02ef6fa30354154bd2f)

Then in `TestAsync.cs` method `RunInsertOrUpdateAsync()`
replace line
`await context.BulkInsertOrUpdateAsync(entities);`
with
`var bulkConfig = new BulkConfig() { SetOutputIdentity = true };`
`await context.BulkInsertOrUpdateAsync(entities/*, bulkConfig*/);`

Then run this test and previous exception is thrown in `TableInfo.cs` method `QueryOutputTableAsync()` on line:
`var result = compiled(context);`

At the moment I can't find a way to make this work unless I remove compiled Query, which would then return memory leak.
Could you take a look.

**Comment by JanEggers** [comment]
sry @borisdj thought I tested it when updating the async tests but didnt think of adding the SetOutputIdentity = true

anyway I just had to pick the correct overload and now async is working fine

**Comment by borisdj** [comment]
Fix integrated and Nuget 2.1.8 published

**Comment by JanEggers** [comment]
thx again awesome package btw we get more than 12x of regular EF update performance with this

**Comment by borisdj** [comment]
You are welcome. I'm glad it's useful.
