### ISSUE TITLE
Add ability to know how many records were inserted and how many were updated on a BulkInsertOrUpdate call

### ISSUE THREAD

**Issue by fsmirne** [borisdj/EFCore.BulkExtensions#74]
BulkInsertOrUpdate should have an option to return how many records were inserted and how many were updated. It seem like the code is already keeping track of this internally, but I believe there should be a way to extract that information after the call has been completed.
Thanks!

**Comment by borisdj** [comment]
I assume you are doing insert/update by some unique column(s).
At the moment you can set _SetOutputIdentity_ to True in **BulkConfig** which will load back inserted data. This will give you Id created by Db (int type, autoincrement).
Now there is no explicit info which ones were inserted and which were updated, and I am not sure how to check for this in the library itself.
But I believe you can split that list into 2 these 2 group after BulkInsertOrUpdate().
One way would be to use Id(s). If it was _int_ type then before inserting get last Id and all those that have Id > LastId are inserted, others were update.
On the other hand If Id is of type _Guid_, SeqGuid created not in Db but in application, which you would have to set for all items in list, and then after function is executed those that have Id value, would be ones that were updated, because Id was loaded from existing record.

However I have another procedure for situation like this.
I first load records in memory into a dictionary where key is joined string of unique columns.
Then make separation of Insert group and Update group.
It is done so that Audit columns (CreatedTime, UpdatedTime) could be properly set.
This approach requires loading existing records into memory, options to do it:
1. Load all - feasible only if table is not very big.
2. Load only ones for update
    2.a) Use Join or Where with Contains (more info in ReadMe) - translated to Sql IN
    2.b) Use BulkRead - I am currently adding this method, and it will be published in a few days.

**Comment by fsmirne** [comment]
Hey @borisdj thanks for your reply.
I was thinking more along the lines of [this solution](https://stackoverflow.com/questions/1268491/sql-server-2008-merge-best-way-to-get-counts).

Loading all records in memory is not a good solution for this case as the number of records can be very large. I think the most efficient way to get this info is to get the info as the operation is done as in the url above.

Thanks for your help!

**Comment by borisdj** [comment]
I'll take a look.

**Comment by fsmirne** [comment]
I cloned your repository and hacked the code a bit without any design in mind. I got it to work and performance was descent. I tested a few different scenarios using tempdb and not.
Take a look at [this link](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/c06e1db4-7fd6-43c4-8569-5335d555dac8/record-count-on-merge-statement-on-insertupdatedelete?forum=transactsql) especially the solution by **Rahul Sherawat**. I think this could be become a new option where you can get the stats on the action performed if you'd like since it does increase overhead. That way people can choose it depend on their scenario.

Let me know if you'd like me to share my hack and I'll be glad to commit it to github...
Thanks!

**Comment by JanEggers** [comment]
I dont think its a good Idea to bring dapper as a dependency into a package that should work with EF ....

**Comment by fsmirne** [comment]
@JanEggers for sure. It was the easiest way to map the data of the temp table to a class object we can return.
As I said, it was just a hack and could use a proper design, but I think this is a good proof of concept and I think the project can benefit from an option like that...

**Comment by fsmirne** [comment]
I just merged your latest changes so everything is updated and compiles.
If you guys can figure out a way to get rid of Dapper and make everything work with `ExecuteSqlCommand`, I think everything we would be in good shape.

**Comment by fsmirne** [comment]
Hey @borisdj,
I made some changes to my commit to remove the dependency on Dapper. I'll create a pull request to help out with the merge. Hope this helps!

**Comment by borisdj** [comment]
Ability added.
In BulkConfig thete is now **CalculateStats** which when is set to True result is return in object 'BulkConfig.StatsInfo', params: (_StatsNumberInserted_ and _StatsNumberUpdated_).

**Comment by fsmirne** [comment]
Hey @borisdj,

I like your implementation of it. It's simpler than what I came up with.
One thing that you could improve in the future is to also calculate stats on deletes instead of only inserts and updates since the $action would also take care of that.
Thanks for your good work!

**Comment by borisdj** [comment]
I'll see to add it with next version.
You are welcome.

**Comment by borisdj** [comment]
It should work even if only one is set.
If there is some problem then could be a bug, but I have just tested it with only **CalculateStats** = True, and it in _StatsInfo_ I got the result.

**Comment by borisdj** [comment]
It's a bug then.
I thought it works because I tested it with only Import list of 1000, and got results 1000/0 but that was only because bit IsUpdate is false by defualt.
Instead of
`if (tableInfo.BulkConfig.SetOutputIdentity)`
it shoud be
`if (tableInfo.CreatedOutputTable)`
