### ISSUE TITLE
BulkInsert reset NotMapped Property with SetOutputIdentity = true

### ISSUE THREAD

**Issue by lfongaroScp** [borisdj/EFCore.BulkExtensions#76]
Hi,

Let me explain with an Example.

```
class Foo {
public int Id {get; set;}
//other field 

[NotMapper]
public stringNotTouch {get; set;}
}
```

```
List<Foo> items; 
//initialize the list

using (var transaction = context.Database.BeginTransaction()) {
//here the field stringNotTouch has value, id is 0
context.BulkInsert(itemList, , new BulkConfig { SetOutputIdentity = true });
//here the field stringNotTouch has _no_ value, but id is valid
 transaction.Commit();
 }

```

Is it a bug?

**Comment by borisdj** [comment]
No classic bug, but we could say it's unusual behavior.
What happens here is that when in _BulkConfig_ only **SetOutputIdentity** = True, entity list is reload from Db and that's why `NotMapped` Properties are null.
However there is also **PreserveInsertOrder** property and when both are set then list will be updated from Db and as a consequence `NotMapped` Properties will keep their values.
So if you have `NotMapped` Properties and want to keep their values just set this Property also.
In README is more info about setting Id-s (to negative values) of entities when PreserveInsertOrder is used.
