### ISSUE TITLE
bulkinsert problem with timestamp column and SetOutputIdentity=true config

### ISSUE THREAD

**Issue by ahmad-rahimi** [borisdj/EFCore.BulkExtensions#87]
**nuget version 2.1.8**

**error**
System.Data.SqlClient.SqlException: 'Cannot insert an explicit value into a timestamp column. Use INSERT with a column list to exclude the timestamp column, or insert a DEFAULT into the timestamp column.'

**insert command**
`context.BulkInsert(dataList, new BulkConfig { SetOutputIdentity = true, BatchSize = 10000, PropertiesToExclude= new List<string> { "RowVersion" } });`

i use ulong data type for RowVersion column in the model with conversion configured for that column

**model configuration**
`modelBuilder.Entity<Bank>().Property<ulong>(x => x.RowVersion).HasColumnName(@"RowVersion").HasColumnType(@"timestamp").HasConversion(new NumberToBytesConverter<ulong>()).ValueGeneratedOnAddOrUpdate();`

i don't use this column for Concurrency checking

error occurs only if SetOutputIdentity is true

**Comment by borisdj** [comment]
I am unable to reproduce this.
Also you do not need Timestamp properties in PropertiesToExclude since they are automatically excluded, which is explained in ReadMe:
`With Computed and Timestamp Columns it will work in a way that they are automatically excluded from Insert. And when combined with SetOutputIdentity then ComputedColumns will be Selected while Timestamp will not (it stays Null).`
In the library source there is a Test: InsertWithDbComputedColumnsAndOutput for this so you can check there that it works, or try to change code to reproduce it.

**Comment by borisdj** [comment]
Actually I see now why you got this error.
It's because of the column type.
Instead of `ulong` it should be `byte[]`;
[http://www.entityframeworktutorial.net/code-first/TimeStamp-dataannotations-attribute-in-code-first.aspx](http://www.entityframeworktutorial.net/code-first/TimeStamp-dataannotations-attribute-in-code-first.aspx)
