### ISSUE TITLE
Throws SqlException: Login failed for user '....'.

### ISSUE THREAD

**Issue by nafberger** [borisdj/EFCore.BulkExtensions#9]
I tried using this extension. I included a copy of  my code, see screenshot, it throws user login failed, what am I doing wrong. please contact me on nafberger@gmail.com
![screenshot_1](https://user-images.githubusercontent.com/26122027/27997317-ee9ddc58-64c3-11e7-9c9c-75dbf4bb711d.png)

**Comment by borisdj** [comment]
Take a look at this [issue](https://github.com/borisdj/EFCore.BulkExtensions/issues/4).
Do you have installed _System.Data.SqlClient_ library in the project.
Also try setting _Persist Security Info_ to  _true_ in ConnectionString.
Otherwise could you make a sample project where the problem is manifesting and zip it on Drive or Dropbox and send a link.

**Comment by nafberger** [comment]
Huge Huge Thanks. persist security info was the key. It Works.

**Comment by borisdj** [comment]
You are welcome.

**Comment by nafberger** [comment]
Hi Borris, How does BulkUpdate Work, do you need first to get the existing entry, make the changes, add it to list, and at the end of the work pass it in to BulkUpdate. Or can you just pass in a list of entities and the computer figures it out by itself. Please clarify

**Comment by borisdj** [comment]
Update is done by matching **PrimaryKey**, so if you already know/have PKs than just pass that list.
Otherwise you need to do Select to get Entites with their PK.
